/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * AuthorizeSGroupEgressApiRequestSchemaRule
 */

public class AuthorizeSGroupEgressApiRequestSchemaRule {
  @JsonProperty("GroupName")
  private String groupName = null;

  @JsonProperty("IpPermissions.N")
  private List<AuthorizeSGroupEgressApiRequestSchemaRuleIpPermissionsN> ipPermissionsN = null;

  public AuthorizeSGroupEgressApiRequestSchemaRule groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * name of the security group
   * @return groupName
  **/
  @ApiModelProperty(example = "", value = "name of the security group")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public AuthorizeSGroupEgressApiRequestSchemaRule ipPermissionsN(List<AuthorizeSGroupEgressApiRequestSchemaRuleIpPermissionsN> ipPermissionsN) {
    this.ipPermissionsN = ipPermissionsN;
    return this;
  }

  public AuthorizeSGroupEgressApiRequestSchemaRule addIpPermissionsNItem(AuthorizeSGroupEgressApiRequestSchemaRuleIpPermissionsN ipPermissionsNItem) {
    if (this.ipPermissionsN == null) {
      this.ipPermissionsN = new ArrayList<>();
    }
    this.ipPermissionsN.add(ipPermissionsNItem);
    return this;
  }

   /**
   * sets of ip permission
   * @return ipPermissionsN
  **/
  @ApiModelProperty(value = "sets of ip permission")
  public List<AuthorizeSGroupEgressApiRequestSchemaRuleIpPermissionsN> getIpPermissionsN() {
    return ipPermissionsN;
  }

  public void setIpPermissionsN(List<AuthorizeSGroupEgressApiRequestSchemaRuleIpPermissionsN> ipPermissionsN) {
    this.ipPermissionsN = ipPermissionsN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizeSGroupEgressApiRequestSchemaRule authorizeSGroupEgressApiRequestSchemaRule = (AuthorizeSGroupEgressApiRequestSchemaRule) o;
    return Objects.equals(this.groupName, authorizeSGroupEgressApiRequestSchemaRule.groupName) &&
        Objects.equals(this.ipPermissionsN, authorizeSGroupEgressApiRequestSchemaRule.ipPermissionsN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, ipPermissionsN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizeSGroupEgressApiRequestSchemaRule {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    ipPermissionsN: ").append(toIndentedString(ipPermissionsN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

