/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * AuthorizeSGroupIngressApiResponseSchema
 */

public class AuthorizeSGroupIngressApiResponseSchema {
  @JsonProperty("AuthorizeSecurityGroupIngressResponse")
  private AuthorizeSGroupIngressApiResponseSchemaAuthorizeSecurityGroupIngressResponse authorizeSecurityGroupIngressResponse = null;

  public AuthorizeSGroupIngressApiResponseSchema authorizeSecurityGroupIngressResponse(AuthorizeSGroupIngressApiResponseSchemaAuthorizeSecurityGroupIngressResponse authorizeSecurityGroupIngressResponse) {
    this.authorizeSecurityGroupIngressResponse = authorizeSecurityGroupIngressResponse;
    return this;
  }

   /**
   * Get authorizeSecurityGroupIngressResponse
   * @return authorizeSecurityGroupIngressResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public AuthorizeSGroupIngressApiResponseSchemaAuthorizeSecurityGroupIngressResponse getAuthorizeSecurityGroupIngressResponse() {
    return authorizeSecurityGroupIngressResponse;
  }

  public void setAuthorizeSecurityGroupIngressResponse(AuthorizeSGroupIngressApiResponseSchemaAuthorizeSecurityGroupIngressResponse authorizeSecurityGroupIngressResponse) {
    this.authorizeSecurityGroupIngressResponse = authorizeSecurityGroupIngressResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizeSGroupIngressApiResponseSchema authorizeSGroupIngressApiResponseSchema = (AuthorizeSGroupIngressApiResponseSchema) o;
    return Objects.equals(this.authorizeSecurityGroupIngressResponse, authorizeSGroupIngressApiResponseSchema.authorizeSecurityGroupIngressResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizeSecurityGroupIngressResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizeSGroupIngressApiResponseSchema {\n");
    
    sb.append("    authorizeSecurityGroupIngressResponse: ").append(toIndentedString(authorizeSecurityGroupIngressResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

