/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse
 */

public class ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse {
  @JsonProperty("ChangeDBInstanceUserPasswordResult")
  private ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseChangeDBInstanceUserPasswordResult changeDBInstanceUserPasswordResult = null;

  @JsonProperty("ResponseMetadata")
  private ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseResponseMetadata responseMetadata = null;

  @JsonProperty("__xmlns")
  private String xmlns = null;

  public ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse changeDBInstanceUserPasswordResult(ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseChangeDBInstanceUserPasswordResult changeDBInstanceUserPasswordResult) {
    this.changeDBInstanceUserPasswordResult = changeDBInstanceUserPasswordResult;
    return this;
  }

   /**
   * Get changeDBInstanceUserPasswordResult
   * @return changeDBInstanceUserPasswordResult
  **/
  @ApiModelProperty(value = "")
  public ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseChangeDBInstanceUserPasswordResult getChangeDBInstanceUserPasswordResult() {
    return changeDBInstanceUserPasswordResult;
  }

  public void setChangeDBInstanceUserPasswordResult(ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseChangeDBInstanceUserPasswordResult changeDBInstanceUserPasswordResult) {
    this.changeDBInstanceUserPasswordResult = changeDBInstanceUserPasswordResult;
  }

  public ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse responseMetadata(ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseResponseMetadata responseMetadata) {
    this.responseMetadata = responseMetadata;
    return this;
  }

   /**
   * Get responseMetadata
   * @return responseMetadata
  **/
  @ApiModelProperty(value = "")
  public ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseResponseMetadata getResponseMetadata() {
    return responseMetadata;
  }

  public void setResponseMetadata(ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponseResponseMetadata responseMetadata) {
    this.responseMetadata = responseMetadata;
  }

  public ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse xmlns(String xmlns) {
    this.xmlns = xmlns;
    return this;
  }

   /**
   * Get xmlns
   * @return xmlns
  **/
  @ApiModelProperty(value = "")
  public String getXmlns() {
    return xmlns;
  }

  public void setXmlns(String xmlns) {
    this.xmlns = xmlns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse changeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse = (ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse) o;
    return Objects.equals(this.changeDBInstanceUserPasswordResult, changeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse.changeDBInstanceUserPasswordResult) &&
        Objects.equals(this.responseMetadata, changeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse.responseMetadata) &&
        Objects.equals(this.xmlns, changeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse.xmlns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeDBInstanceUserPasswordResult, responseMetadata, xmlns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeDBInstanceUserPasswordApiV2ResponseSchemaChangeDBInstanceUserPasswordResponse {\n");
    
    sb.append("    changeDBInstanceUserPasswordResult: ").append(toIndentedString(changeDBInstanceUserPasswordResult)).append("\n");
    sb.append("    responseMetadata: ").append(toIndentedString(responseMetadata)).append("\n");
    sb.append("    xmlns: ").append(toIndentedString(xmlns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

