/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateAppInstancesResponseSchema
 */

public class CreateAppInstancesResponseSchema {
  @JsonProperty("CreateAppInstanceResponse")
  private CreateAppInstancesResponseSchemaCreateAppInstanceResponse createAppInstanceResponse = null;

  public CreateAppInstancesResponseSchema createAppInstanceResponse(CreateAppInstancesResponseSchemaCreateAppInstanceResponse createAppInstanceResponse) {
    this.createAppInstanceResponse = createAppInstanceResponse;
    return this;
  }

   /**
   * Get createAppInstanceResponse
   * @return createAppInstanceResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public CreateAppInstancesResponseSchemaCreateAppInstanceResponse getCreateAppInstanceResponse() {
    return createAppInstanceResponse;
  }

  public void setCreateAppInstanceResponse(CreateAppInstancesResponseSchemaCreateAppInstanceResponse createAppInstanceResponse) {
    this.createAppInstanceResponse = createAppInstanceResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAppInstancesResponseSchema createAppInstancesResponseSchema = (CreateAppInstancesResponseSchema) o;
    return Objects.equals(this.createAppInstanceResponse, createAppInstancesResponseSchema.createAppInstanceResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createAppInstanceResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAppInstancesResponseSchema {\n");
    
    sb.append("    createAppInstanceResponse: ").append(toIndentedString(createAppInstanceResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

