/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateSecurityGroupApiRequestSchemaSecurityGroup
 */

public class CreateSecurityGroupApiRequestSchemaSecurityGroup {
  @JsonProperty("GroupDescription")
  private String groupDescription = null;

  @JsonProperty("GroupName")
  private String groupName = null;

  @JsonProperty("GroupType")
  private String groupType = null;

  @JsonProperty("VpcId")
  private String vpcId = null;

  public CreateSecurityGroupApiRequestSchemaSecurityGroup groupDescription(String groupDescription) {
    this.groupDescription = groupDescription;
    return this;
  }

   /**
   * a description for the security group
   * @return groupDescription
  **/
  @ApiModelProperty(example = "", value = "a description for the security group")
  public String getGroupDescription() {
    return groupDescription;
  }

  public void setGroupDescription(String groupDescription) {
    this.groupDescription = groupDescription;
  }

  public CreateSecurityGroupApiRequestSchemaSecurityGroup groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * name of the security group
   * @return groupName
  **/
  @ApiModelProperty(example = "", required = true, value = "name of the security group")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public CreateSecurityGroupApiRequestSchemaSecurityGroup groupType(String groupType) {
    this.groupType = groupType;
    return this;
  }

   /**
   * security group template
   * @return groupType
  **/
  @ApiModelProperty(value = "security group template")
  public String getGroupType() {
    return groupType;
  }

  public void setGroupType(String groupType) {
    this.groupType = groupType;
  }

  public CreateSecurityGroupApiRequestSchemaSecurityGroup vpcId(String vpcId) {
    this.vpcId = vpcId;
    return this;
  }

   /**
   * ID of the VPC
   * @return vpcId
  **/
  @ApiModelProperty(example = "", required = true, value = "ID of the VPC")
  public String getVpcId() {
    return vpcId;
  }

  public void setVpcId(String vpcId) {
    this.vpcId = vpcId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSecurityGroupApiRequestSchemaSecurityGroup createSecurityGroupApiRequestSchemaSecurityGroup = (CreateSecurityGroupApiRequestSchemaSecurityGroup) o;
    return Objects.equals(this.groupDescription, createSecurityGroupApiRequestSchemaSecurityGroup.groupDescription) &&
        Objects.equals(this.groupName, createSecurityGroupApiRequestSchemaSecurityGroup.groupName) &&
        Objects.equals(this.groupType, createSecurityGroupApiRequestSchemaSecurityGroup.groupType) &&
        Objects.equals(this.vpcId, createSecurityGroupApiRequestSchemaSecurityGroup.vpcId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupDescription, groupName, groupType, vpcId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSecurityGroupApiRequestSchemaSecurityGroup {\n");
    
    sb.append("    groupDescription: ").append(toIndentedString(groupDescription)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    groupType: ").append(toIndentedString(groupType)).append("\n");
    sb.append("    vpcId: ").append(toIndentedString(vpcId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

