/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.math.BigDecimal;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateServiceScheduleRequestSchemaJobScheduleScheduleParams
 */

public class CreateServiceScheduleRequestSchemaJobScheduleScheduleParams {
  @JsonProperty("day_of_month")
  private String dayOfMonth = null;

  @JsonProperty("day_of_week")
  private String dayOfWeek = null;

  @JsonProperty("days")
  private BigDecimal days = null;

  @JsonProperty("hour")
  private String hour = null;

  @JsonProperty("hours")
  private BigDecimal hours = null;

  @JsonProperty("minute")
  private String minute = null;

  @JsonProperty("minutes")
  private BigDecimal minutes = null;

  @JsonProperty("month_of_year")
  private String monthOfYear = null;

  @JsonProperty("seconds")
  private BigDecimal seconds = null;

  @JsonProperty("weeks")
  private BigDecimal weeks = null;

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams dayOfMonth(String dayOfMonth) {
    this.dayOfMonth = dayOfMonth;
    return this;
  }

   /**
   * Get dayOfMonth
   * @return dayOfMonth
  **/
  @ApiModelProperty(value = "")
  public String getDayOfMonth() {
    return dayOfMonth;
  }

  public void setDayOfMonth(String dayOfMonth) {
    this.dayOfMonth = dayOfMonth;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams dayOfWeek(String dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
    return this;
  }

   /**
   * Get dayOfWeek
   * @return dayOfWeek
  **/
  @ApiModelProperty(value = "")
  public String getDayOfWeek() {
    return dayOfWeek;
  }

  public void setDayOfWeek(String dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams days(BigDecimal days) {
    this.days = days;
    return this;
  }

   /**
   * Get days
   * @return days
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDays() {
    return days;
  }

  public void setDays(BigDecimal days) {
    this.days = days;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams hour(String hour) {
    this.hour = hour;
    return this;
  }

   /**
   * Get hour
   * @return hour
  **/
  @ApiModelProperty(value = "")
  public String getHour() {
    return hour;
  }

  public void setHour(String hour) {
    this.hour = hour;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams hours(BigDecimal hours) {
    this.hours = hours;
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getHours() {
    return hours;
  }

  public void setHours(BigDecimal hours) {
    this.hours = hours;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams minute(String minute) {
    this.minute = minute;
    return this;
  }

   /**
   * Get minute
   * @return minute
  **/
  @ApiModelProperty(value = "")
  public String getMinute() {
    return minute;
  }

  public void setMinute(String minute) {
    this.minute = minute;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams minutes(BigDecimal minutes) {
    this.minutes = minutes;
    return this;
  }

   /**
   * Get minutes
   * @return minutes
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMinutes() {
    return minutes;
  }

  public void setMinutes(BigDecimal minutes) {
    this.minutes = minutes;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams monthOfYear(String monthOfYear) {
    this.monthOfYear = monthOfYear;
    return this;
  }

   /**
   * Get monthOfYear
   * @return monthOfYear
  **/
  @ApiModelProperty(value = "")
  public String getMonthOfYear() {
    return monthOfYear;
  }

  public void setMonthOfYear(String monthOfYear) {
    this.monthOfYear = monthOfYear;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams seconds(BigDecimal seconds) {
    this.seconds = seconds;
    return this;
  }

   /**
   * Get seconds
   * @return seconds
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSeconds() {
    return seconds;
  }

  public void setSeconds(BigDecimal seconds) {
    this.seconds = seconds;
  }

  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams weeks(BigDecimal weeks) {
    this.weeks = weeks;
    return this;
  }

   /**
   * Get weeks
   * @return weeks
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getWeeks() {
    return weeks;
  }

  public void setWeeks(BigDecimal weeks) {
    this.weeks = weeks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateServiceScheduleRequestSchemaJobScheduleScheduleParams createServiceScheduleRequestSchemaJobScheduleScheduleParams = (CreateServiceScheduleRequestSchemaJobScheduleScheduleParams) o;
    return Objects.equals(this.dayOfMonth, createServiceScheduleRequestSchemaJobScheduleScheduleParams.dayOfMonth) &&
        Objects.equals(this.dayOfWeek, createServiceScheduleRequestSchemaJobScheduleScheduleParams.dayOfWeek) &&
        Objects.equals(this.days, createServiceScheduleRequestSchemaJobScheduleScheduleParams.days) &&
        Objects.equals(this.hour, createServiceScheduleRequestSchemaJobScheduleScheduleParams.hour) &&
        Objects.equals(this.hours, createServiceScheduleRequestSchemaJobScheduleScheduleParams.hours) &&
        Objects.equals(this.minute, createServiceScheduleRequestSchemaJobScheduleScheduleParams.minute) &&
        Objects.equals(this.minutes, createServiceScheduleRequestSchemaJobScheduleScheduleParams.minutes) &&
        Objects.equals(this.monthOfYear, createServiceScheduleRequestSchemaJobScheduleScheduleParams.monthOfYear) &&
        Objects.equals(this.seconds, createServiceScheduleRequestSchemaJobScheduleScheduleParams.seconds) &&
        Objects.equals(this.weeks, createServiceScheduleRequestSchemaJobScheduleScheduleParams.weeks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dayOfMonth, dayOfWeek, days, hour, hours, minute, minutes, monthOfYear, seconds, weeks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateServiceScheduleRequestSchemaJobScheduleScheduleParams {\n");
    
    sb.append("    dayOfMonth: ").append(toIndentedString(dayOfMonth)).append("\n");
    sb.append("    dayOfWeek: ").append(toIndentedString(dayOfWeek)).append("\n");
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    minute: ").append(toIndentedString(minute)).append("\n");
    sb.append("    minutes: ").append(toIndentedString(minutes)).append("\n");
    sb.append("    monthOfYear: ").append(toIndentedString(monthOfYear)).append("\n");
    sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
    sb.append("    weeks: ").append(toIndentedString(weeks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

