/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateServiceProcessRequestSchemaServiceprocess
 */

public class CreateServiceProcessRequestSchemaServiceprocess {
  @JsonProperty("desc")
  private String desc = null;

  @JsonProperty("method_key")
  private String methodKey = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("process_key")
  private String processKey = null;

  @JsonProperty("service_type_id")
  private String serviceTypeId = null;

  @JsonProperty("template")
  private String template = null;

  public CreateServiceProcessRequestSchemaServiceprocess desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @ApiModelProperty(value = "")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public CreateServiceProcessRequestSchemaServiceprocess methodKey(String methodKey) {
    this.methodKey = methodKey;
    return this;
  }

   /**
   * Get methodKey
   * @return methodKey
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMethodKey() {
    return methodKey;
  }

  public void setMethodKey(String methodKey) {
    this.methodKey = methodKey;
  }

  public CreateServiceProcessRequestSchemaServiceprocess name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateServiceProcessRequestSchemaServiceprocess processKey(String processKey) {
    this.processKey = processKey;
    return this;
  }

   /**
   * Get processKey
   * @return processKey
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProcessKey() {
    return processKey;
  }

  public void setProcessKey(String processKey) {
    this.processKey = processKey;
  }

  public CreateServiceProcessRequestSchemaServiceprocess serviceTypeId(String serviceTypeId) {
    this.serviceTypeId = serviceTypeId;
    return this;
  }

   /**
   * Get serviceTypeId
   * @return serviceTypeId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getServiceTypeId() {
    return serviceTypeId;
  }

  public void setServiceTypeId(String serviceTypeId) {
    this.serviceTypeId = serviceTypeId;
  }

  public CreateServiceProcessRequestSchemaServiceprocess template(String template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateServiceProcessRequestSchemaServiceprocess createServiceProcessRequestSchemaServiceprocess = (CreateServiceProcessRequestSchemaServiceprocess) o;
    return Objects.equals(this.desc, createServiceProcessRequestSchemaServiceprocess.desc) &&
        Objects.equals(this.methodKey, createServiceProcessRequestSchemaServiceprocess.methodKey) &&
        Objects.equals(this.name, createServiceProcessRequestSchemaServiceprocess.name) &&
        Objects.equals(this.processKey, createServiceProcessRequestSchemaServiceprocess.processKey) &&
        Objects.equals(this.serviceTypeId, createServiceProcessRequestSchemaServiceprocess.serviceTypeId) &&
        Objects.equals(this.template, createServiceProcessRequestSchemaServiceprocess.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desc, methodKey, name, processKey, serviceTypeId, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateServiceProcessRequestSchemaServiceprocess {\n");
    
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    methodKey: ").append(toIndentedString(methodKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    processKey: ").append(toIndentedString(processKey)).append("\n");
    sb.append("    serviceTypeId: ").append(toIndentedString(serviceTypeId)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

