/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateBackupRestoreApiRequestSchemaInstance
 */

public class CreateBackupRestoreApiRequestSchemaInstance {
  @JsonProperty("InstanceId")
  private String instanceId = null;

  @JsonProperty("InstanceName")
  private String instanceName = null;

  @JsonProperty("RestorePointId")
  private String restorePointId = null;

  @JsonProperty("owner-id")
  private String ownerId = null;

  public CreateBackupRestoreApiRequestSchemaInstance instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * id of the instance to restore
   * @return instanceId
  **/
  @ApiModelProperty(required = true, value = "id of the instance to restore")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public CreateBackupRestoreApiRequestSchemaInstance instanceName(String instanceName) {
    this.instanceName = instanceName;
    return this;
  }

   /**
   * restored instance name
   * @return instanceName
  **/
  @ApiModelProperty(example = "test", required = true, value = "restored instance name")
  public String getInstanceName() {
    return instanceName;
  }

  public void setInstanceName(String instanceName) {
    this.instanceName = instanceName;
  }

  public CreateBackupRestoreApiRequestSchemaInstance restorePointId(String restorePointId) {
    this.restorePointId = restorePointId;
    return this;
  }

   /**
   * id of the restore point to use
   * @return restorePointId
  **/
  @ApiModelProperty(required = true, value = "id of the restore point to use")
  public String getRestorePointId() {
    return restorePointId;
  }

  public void setRestorePointId(String restorePointId) {
    this.restorePointId = restorePointId;
  }

  public CreateBackupRestoreApiRequestSchemaInstance ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * account ID of the instance owner
   * @return ownerId
  **/
  @ApiModelProperty(value = "account ID of the instance owner")
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackupRestoreApiRequestSchemaInstance createBackupRestoreApiRequestSchemaInstance = (CreateBackupRestoreApiRequestSchemaInstance) o;
    return Objects.equals(this.instanceId, createBackupRestoreApiRequestSchemaInstance.instanceId) &&
        Objects.equals(this.instanceName, createBackupRestoreApiRequestSchemaInstance.instanceName) &&
        Objects.equals(this.restorePointId, createBackupRestoreApiRequestSchemaInstance.restorePointId) &&
        Objects.equals(this.ownerId, createBackupRestoreApiRequestSchemaInstance.ownerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceId, instanceName, restorePointId, ownerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackupRestoreApiRequestSchemaInstance {\n");
    
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    instanceName: ").append(toIndentedString(instanceName)).append("\n");
    sb.append("    restorePointId: ").append(toIndentedString(restorePointId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

