/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")

public class CreateDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("pwd")
  private String pwd = null;

  public CreateDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername name(String name) {
    this.name = name;
    return this;
  }

   /**
   * master username name
   * @return name
  **/
  @ApiModelProperty(value = "master username name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername pwd(String pwd) {
    this.pwd = pwd;
    return this;
  }

   /**
   * master username password
   * @return pwd
  **/
  @ApiModelProperty(value = "master username password")
  public String getPwd() {
    return pwd;
  }

  public void setPwd(String pwd) {
    this.pwd = pwd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername createDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername = (CreateDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername) o;
    return Objects.equals(this.name, createDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername.name) &&
        Objects.equals(this.pwd, createDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername.pwd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, pwd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDBInstanceV2ResponseSchemaCreateDBInstanceResponseCreateDBInstanceResultDBInstanceMasterUsername {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pwd: ").append(toIndentedString(pwd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

