/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateVpcApiResponseSchema
 */

public class CreateVpcApiResponseSchema {
  @JsonProperty("CreateVpcResponse")
  private CreateImageApiResponseSchemaCreateImageResponse createVpcResponse = null;

  public CreateVpcApiResponseSchema createVpcResponse(CreateImageApiResponseSchemaCreateImageResponse createVpcResponse) {
    this.createVpcResponse = createVpcResponse;
    return this;
  }

   /**
   * Get createVpcResponse
   * @return createVpcResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public CreateImageApiResponseSchemaCreateImageResponse getCreateVpcResponse() {
    return createVpcResponse;
  }

  public void setCreateVpcResponse(CreateImageApiResponseSchemaCreateImageResponse createVpcResponse) {
    this.createVpcResponse = createVpcResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVpcApiResponseSchema createVpcApiResponseSchema = (CreateVpcApiResponseSchema) o;
    return Objects.equals(this.createVpcResponse, createVpcApiResponseSchema.createVpcResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createVpcResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVpcApiResponseSchema {\n");
    
    sb.append("    createVpcResponse: ").append(toIndentedString(createVpcResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

