/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateTemplateApiRequestSchemaTemplate
 */

public class CreateTemplateApiRequestSchemaTemplate {
  @JsonProperty("desc")
  private String desc = null;

  @JsonProperty("job_template_id")
  private String jobTemplateId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("owner_id")
  private String ownerId = null;

  @JsonProperty("template_type")
  private String templateType = null;

  public CreateTemplateApiRequestSchemaTemplate desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * description of the template
   * @return desc
  **/
  @ApiModelProperty(example = "", value = "description of the template")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public CreateTemplateApiRequestSchemaTemplate jobTemplateId(String jobTemplateId) {
    this.jobTemplateId = jobTemplateId;
    return this;
  }

   /**
   * job template id
   * @return jobTemplateId
  **/
  @ApiModelProperty(example = "", required = true, value = "job template id")
  public String getJobTemplateId() {
    return jobTemplateId;
  }

  public void setJobTemplateId(String jobTemplateId) {
    this.jobTemplateId = jobTemplateId;
  }

  public CreateTemplateApiRequestSchemaTemplate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the template
   * @return name
  **/
  @ApiModelProperty(example = "", required = true, value = "name of the template")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateTemplateApiRequestSchemaTemplate ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * account id
   * @return ownerId
  **/
  @ApiModelProperty(example = "", required = true, value = "account id")
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  public CreateTemplateApiRequestSchemaTemplate templateType(String templateType) {
    this.templateType = templateType;
    return this;
  }

   /**
   * template definition
   * @return templateType
  **/
  @ApiModelProperty(value = "template definition")
  public String getTemplateType() {
    return templateType;
  }

  public void setTemplateType(String templateType) {
    this.templateType = templateType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTemplateApiRequestSchemaTemplate createTemplateApiRequestSchemaTemplate = (CreateTemplateApiRequestSchemaTemplate) o;
    return Objects.equals(this.desc, createTemplateApiRequestSchemaTemplate.desc) &&
        Objects.equals(this.jobTemplateId, createTemplateApiRequestSchemaTemplate.jobTemplateId) &&
        Objects.equals(this.name, createTemplateApiRequestSchemaTemplate.name) &&
        Objects.equals(this.ownerId, createTemplateApiRequestSchemaTemplate.ownerId) &&
        Objects.equals(this.templateType, createTemplateApiRequestSchemaTemplate.templateType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desc, jobTemplateId, name, ownerId, templateType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTemplateApiRequestSchemaTemplate {\n");
    
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    jobTemplateId: ").append(toIndentedString(jobTemplateId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    templateType: ").append(toIndentedString(templateType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

