/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreateServiceScheduleRequestSchemaJobSchedule
 */

public class CreateServiceScheduleRequestSchemaJobSchedule {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("desc")
  private String desc = null;

  @JsonProperty("job_args")
  private Object jobArgs = null;

  @JsonProperty("job_kvargs")
  private Object jobKvargs = null;

  @JsonProperty("job_name")
  private String jobName = null;

  @JsonProperty("job_options")
  private Object jobOptions = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("relative")
  private Boolean relative = null;

  @JsonProperty("retry")
  private Boolean retry = null;

  @JsonProperty("retry_policy")
  private CreateServiceScheduleRequestSchemaJobScheduleRetryPolicy retryPolicy = null;

  @JsonProperty("schedule_params")
  private CreateServiceScheduleRequestSchemaJobScheduleScheduleParams scheduleParams = null;

  /**
   * Gets or Sets scheduleType
   */
  public enum ScheduleTypeEnum {
    CRONTAB("crontab"),
    
    TIMEDELTA("timedelta");

    private String value;

    ScheduleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScheduleTypeEnum fromValue(String value) {
      for (ScheduleTypeEnum b : ScheduleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("schedule_type")
  private ScheduleTypeEnum scheduleType = null;

  public CreateServiceScheduleRequestSchemaJobSchedule active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @ApiModelProperty(value = "")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule jobArgs(Object jobArgs) {
    this.jobArgs = jobArgs;
    return this;
  }

   /**
   * Get jobArgs
   * @return jobArgs
  **/
  @ApiModelProperty(value = "")
  public Object getJobArgs() {
    return jobArgs;
  }

  public void setJobArgs(Object jobArgs) {
    this.jobArgs = jobArgs;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule jobKvargs(Object jobKvargs) {
    this.jobKvargs = jobKvargs;
    return this;
  }

   /**
   * Get jobKvargs
   * @return jobKvargs
  **/
  @ApiModelProperty(value = "")
  public Object getJobKvargs() {
    return jobKvargs;
  }

  public void setJobKvargs(Object jobKvargs) {
    this.jobKvargs = jobKvargs;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule jobName(String jobName) {
    this.jobName = jobName;
    return this;
  }

   /**
   * Get jobName
   * @return jobName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule jobOptions(Object jobOptions) {
    this.jobOptions = jobOptions;
    return this;
  }

   /**
   * Get jobOptions
   * @return jobOptions
  **/
  @ApiModelProperty(value = "")
  public Object getJobOptions() {
    return jobOptions;
  }

  public void setJobOptions(Object jobOptions) {
    this.jobOptions = jobOptions;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule relative(Boolean relative) {
    this.relative = relative;
    return this;
  }

   /**
   * Get relative
   * @return relative
  **/
  @ApiModelProperty(value = "")
  public Boolean isRelative() {
    return relative;
  }

  public void setRelative(Boolean relative) {
    this.relative = relative;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule retry(Boolean retry) {
    this.retry = retry;
    return this;
  }

   /**
   * Get retry
   * @return retry
  **/
  @ApiModelProperty(value = "")
  public Boolean isRetry() {
    return retry;
  }

  public void setRetry(Boolean retry) {
    this.retry = retry;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule retryPolicy(CreateServiceScheduleRequestSchemaJobScheduleRetryPolicy retryPolicy) {
    this.retryPolicy = retryPolicy;
    return this;
  }

   /**
   * Get retryPolicy
   * @return retryPolicy
  **/
  @ApiModelProperty(value = "")
  public CreateServiceScheduleRequestSchemaJobScheduleRetryPolicy getRetryPolicy() {
    return retryPolicy;
  }

  public void setRetryPolicy(CreateServiceScheduleRequestSchemaJobScheduleRetryPolicy retryPolicy) {
    this.retryPolicy = retryPolicy;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule scheduleParams(CreateServiceScheduleRequestSchemaJobScheduleScheduleParams scheduleParams) {
    this.scheduleParams = scheduleParams;
    return this;
  }

   /**
   * Get scheduleParams
   * @return scheduleParams
  **/
  @ApiModelProperty(required = true, value = "")
  public CreateServiceScheduleRequestSchemaJobScheduleScheduleParams getScheduleParams() {
    return scheduleParams;
  }

  public void setScheduleParams(CreateServiceScheduleRequestSchemaJobScheduleScheduleParams scheduleParams) {
    this.scheduleParams = scheduleParams;
  }

  public CreateServiceScheduleRequestSchemaJobSchedule scheduleType(ScheduleTypeEnum scheduleType) {
    this.scheduleType = scheduleType;
    return this;
  }

   /**
   * Get scheduleType
   * @return scheduleType
  **/
  @ApiModelProperty(required = true, value = "")
  public ScheduleTypeEnum getScheduleType() {
    return scheduleType;
  }

  public void setScheduleType(ScheduleTypeEnum scheduleType) {
    this.scheduleType = scheduleType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateServiceScheduleRequestSchemaJobSchedule createServiceScheduleRequestSchemaJobSchedule = (CreateServiceScheduleRequestSchemaJobSchedule) o;
    return Objects.equals(this.active, createServiceScheduleRequestSchemaJobSchedule.active) &&
        Objects.equals(this.desc, createServiceScheduleRequestSchemaJobSchedule.desc) &&
        Objects.equals(this.jobArgs, createServiceScheduleRequestSchemaJobSchedule.jobArgs) &&
        Objects.equals(this.jobKvargs, createServiceScheduleRequestSchemaJobSchedule.jobKvargs) &&
        Objects.equals(this.jobName, createServiceScheduleRequestSchemaJobSchedule.jobName) &&
        Objects.equals(this.jobOptions, createServiceScheduleRequestSchemaJobSchedule.jobOptions) &&
        Objects.equals(this.name, createServiceScheduleRequestSchemaJobSchedule.name) &&
        Objects.equals(this.relative, createServiceScheduleRequestSchemaJobSchedule.relative) &&
        Objects.equals(this.retry, createServiceScheduleRequestSchemaJobSchedule.retry) &&
        Objects.equals(this.retryPolicy, createServiceScheduleRequestSchemaJobSchedule.retryPolicy) &&
        Objects.equals(this.scheduleParams, createServiceScheduleRequestSchemaJobSchedule.scheduleParams) &&
        Objects.equals(this.scheduleType, createServiceScheduleRequestSchemaJobSchedule.scheduleType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, desc, jobArgs, jobKvargs, jobName, jobOptions, name, relative, retry, retryPolicy, scheduleParams, scheduleType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateServiceScheduleRequestSchemaJobSchedule {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    jobArgs: ").append(toIndentedString(jobArgs)).append("\n");
    sb.append("    jobKvargs: ").append(toIndentedString(jobKvargs)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    jobOptions: ").append(toIndentedString(jobOptions)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relative: ").append(toIndentedString(relative)).append("\n");
    sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
    sb.append("    retryPolicy: ").append(toIndentedString(retryPolicy)).append("\n");
    sb.append("    scheduleParams: ").append(toIndentedString(scheduleParams)).append("\n");
    sb.append("    scheduleType: ").append(toIndentedString(scheduleType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

