/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: me@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.time.LocalDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * DeleteBatchConsumeRequestSchemaConsume
 */

public class DeleteBatchConsumeRequestSchemaConsume {
  /**
   * Gets or Sets aggregationType
   */
  public enum AggregationTypeEnum {
    DAILY("daily"),
    
    MONTHLY("monthly");

    private String value;

    AggregationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AggregationTypeEnum fromValue(String text) {
      for (AggregationTypeEnum b : AggregationTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("aggregation_type")
  private AggregationTypeEnum aggregationType = null;

  @JsonProperty("cost_type_id")
  private Integer costTypeId = null;

  @JsonProperty("evaluation_date_end")
  private LocalDateTime evaluationDateEnd = null;

  @JsonProperty("evaluation_date_start")
  private LocalDateTime evaluationDateStart = null;

  @JsonProperty("job_id")
  private Integer jobId = null;

  @JsonProperty("limit")
  private Integer limit = null;

  @JsonProperty("metric_type_id")
  private Integer metricTypeId = null;

  @JsonProperty("period")
  private String period = null;

  @JsonProperty("service_instance_id")
  private String serviceInstanceId = null;

  public DeleteBatchConsumeRequestSchemaConsume aggregationType(AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
    return this;
  }

   /**
   * Get aggregationType
   * @return aggregationType
  **/
  @ApiModelProperty(value = "")
  public AggregationTypeEnum getAggregationType() {
    return aggregationType;
  }

  public void setAggregationType(AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
  }

  public DeleteBatchConsumeRequestSchemaConsume costTypeId(Integer costTypeId) {
    this.costTypeId = costTypeId;
    return this;
  }

   /**
   * Get costTypeId
   * @return costTypeId
  **/
  @ApiModelProperty(value = "")
  public Integer getCostTypeId() {
    return costTypeId;
  }

  public void setCostTypeId(Integer costTypeId) {
    this.costTypeId = costTypeId;
  }

  public DeleteBatchConsumeRequestSchemaConsume evaluationDateEnd(LocalDateTime evaluationDateEnd) {
    this.evaluationDateEnd = evaluationDateEnd;
    return this;
  }

   /**
   * Get evaluationDateEnd
   * @return evaluationDateEnd
  **/
  @ApiModelProperty(example = "1990-12-31T23:59:59Z", value = "")
  public LocalDateTime getEvaluationDateEnd() {
    return evaluationDateEnd;
  }

  public void setEvaluationDateEnd(LocalDateTime evaluationDateEnd) {
    this.evaluationDateEnd = evaluationDateEnd;
  }

  public DeleteBatchConsumeRequestSchemaConsume evaluationDateStart(LocalDateTime evaluationDateStart) {
    this.evaluationDateStart = evaluationDateStart;
    return this;
  }

   /**
   * Get evaluationDateStart
   * @return evaluationDateStart
  **/
  @ApiModelProperty(example = "1990-12-31T23:59:59Z", value = "")
  public LocalDateTime getEvaluationDateStart() {
    return evaluationDateStart;
  }

  public void setEvaluationDateStart(LocalDateTime evaluationDateStart) {
    this.evaluationDateStart = evaluationDateStart;
  }

  public DeleteBatchConsumeRequestSchemaConsume jobId(Integer jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @ApiModelProperty(value = "")
  public Integer getJobId() {
    return jobId;
  }

  public void setJobId(Integer jobId) {
    this.jobId = jobId;
  }

  public DeleteBatchConsumeRequestSchemaConsume limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @ApiModelProperty(value = "")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public DeleteBatchConsumeRequestSchemaConsume metricTypeId(Integer metricTypeId) {
    this.metricTypeId = metricTypeId;
    return this;
  }

   /**
   * Get metricTypeId
   * @return metricTypeId
  **/
  @ApiModelProperty(value = "")
  public Integer getMetricTypeId() {
    return metricTypeId;
  }

  public void setMetricTypeId(Integer metricTypeId) {
    this.metricTypeId = metricTypeId;
  }

  public DeleteBatchConsumeRequestSchemaConsume period(String period) {
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  @ApiModelProperty(value = "")
  public String getPeriod() {
    return period;
  }

  public void setPeriod(String period) {
    this.period = period;
  }

  public DeleteBatchConsumeRequestSchemaConsume serviceInstanceId(String serviceInstanceId) {
    this.serviceInstanceId = serviceInstanceId;
    return this;
  }

   /**
   * Get serviceInstanceId
   * @return serviceInstanceId
  **/
  @ApiModelProperty(value = "")
  public String getServiceInstanceId() {
    return serviceInstanceId;
  }

  public void setServiceInstanceId(String serviceInstanceId) {
    this.serviceInstanceId = serviceInstanceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteBatchConsumeRequestSchemaConsume deleteBatchConsumeRequestSchemaConsume = (DeleteBatchConsumeRequestSchemaConsume) o;
    return Objects.equals(this.aggregationType, deleteBatchConsumeRequestSchemaConsume.aggregationType) &&
        Objects.equals(this.costTypeId, deleteBatchConsumeRequestSchemaConsume.costTypeId) &&
        Objects.equals(this.evaluationDateEnd, deleteBatchConsumeRequestSchemaConsume.evaluationDateEnd) &&
        Objects.equals(this.evaluationDateStart, deleteBatchConsumeRequestSchemaConsume.evaluationDateStart) &&
        Objects.equals(this.jobId, deleteBatchConsumeRequestSchemaConsume.jobId) &&
        Objects.equals(this.limit, deleteBatchConsumeRequestSchemaConsume.limit) &&
        Objects.equals(this.metricTypeId, deleteBatchConsumeRequestSchemaConsume.metricTypeId) &&
        Objects.equals(this.period, deleteBatchConsumeRequestSchemaConsume.period) &&
        Objects.equals(this.serviceInstanceId, deleteBatchConsumeRequestSchemaConsume.serviceInstanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregationType, costTypeId, evaluationDateEnd, evaluationDateStart, jobId, limit, metricTypeId, period, serviceInstanceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteBatchConsumeRequestSchemaConsume {\n");
    
    sb.append("    aggregationType: ").append(toIndentedString(aggregationType)).append("\n");
    sb.append("    costTypeId: ").append(toIndentedString(costTypeId)).append("\n");
    sb.append("    evaluationDateEnd: ").append(toIndentedString(evaluationDateEnd)).append("\n");
    sb.append("    evaluationDateStart: ").append(toIndentedString(evaluationDateStart)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    metricTypeId: ").append(toIndentedString(metricTypeId)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    serviceInstanceId: ").append(toIndentedString(serviceInstanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

