/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DeleteNetworkServiceResponseSchema
 */

public class DeleteNetworkServiceResponseSchema {
  @JsonProperty("taskid")
  private String taskid = null;

  @JsonProperty("uuid")
  private String uuid = null;

  public DeleteNetworkServiceResponseSchema taskid(String taskid) {
    this.taskid = taskid;
    return this;
  }

   /**
   * task id
   * @return taskid
  **/
  @ApiModelProperty(required = true, value = "task id")
  public String getTaskid() {
    return taskid;
  }

  public void setTaskid(String taskid) {
    this.taskid = taskid;
  }

  public DeleteNetworkServiceResponseSchema uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Instance is
   * @return uuid
  **/
  @ApiModelProperty(required = true, value = "Instance is")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteNetworkServiceResponseSchema deleteNetworkServiceResponseSchema = (DeleteNetworkServiceResponseSchema) o;
    return Objects.equals(this.taskid, deleteNetworkServiceResponseSchema.taskid) &&
        Objects.equals(this.uuid, deleteNetworkServiceResponseSchema.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskid, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteNetworkServiceResponseSchema {\n");
    
    sb.append("    taskid: ").append(toIndentedString(taskid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

