/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DeleteLoggingInstanceApiResponseSchema
 */

public class DeleteLoggingInstanceApiResponseSchema {
  @JsonProperty("DeleteInstanceResponse")
  private DeleteLoggingInstanceApiResponseSchemaDeleteInstanceResponse deleteInstanceResponse = null;

  public DeleteLoggingInstanceApiResponseSchema deleteInstanceResponse(DeleteLoggingInstanceApiResponseSchemaDeleteInstanceResponse deleteInstanceResponse) {
    this.deleteInstanceResponse = deleteInstanceResponse;
    return this;
  }

   /**
   * Get deleteInstanceResponse
   * @return deleteInstanceResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public DeleteLoggingInstanceApiResponseSchemaDeleteInstanceResponse getDeleteInstanceResponse() {
    return deleteInstanceResponse;
  }

  public void setDeleteInstanceResponse(DeleteLoggingInstanceApiResponseSchemaDeleteInstanceResponse deleteInstanceResponse) {
    this.deleteInstanceResponse = deleteInstanceResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteLoggingInstanceApiResponseSchema deleteLoggingInstanceApiResponseSchema = (DeleteLoggingInstanceApiResponseSchema) o;
    return Objects.equals(this.deleteInstanceResponse, deleteLoggingInstanceApiResponseSchema.deleteInstanceResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deleteInstanceResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteLoggingInstanceApiResponseSchema {\n");
    
    sb.append("    deleteInstanceResponse: ").append(toIndentedString(deleteInstanceResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

