/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DeleteInstanceSnapshotsApiRequestSchema
 */

public class DeleteInstanceSnapshotsApiRequestSchema {
  @JsonProperty("InstanceId.N")
  private List<String> instanceIdDotN = new ArrayList<>();

  @JsonProperty("SnapshotId")
  private String snapshotId = null;

  @JsonProperty("owner-id.N")
  private List<String> ownerIdN = null;

  public DeleteInstanceSnapshotsApiRequestSchema instanceIdDotN(List<String> instanceIdDotN) {
    this.instanceIdDotN = instanceIdDotN;
    return this;
  }

  public DeleteInstanceSnapshotsApiRequestSchema addInstanceIdDotNItem(String instanceIdDotNItem) {
    this.instanceIdDotN.add(instanceIdDotNItem);
    return this;
  }

   /**
   * instance id
   * @return instanceIdDotN
  **/
  @ApiModelProperty(required = true, value = "instance id")
  public List<String> getInstanceIdDotN() {
    return instanceIdDotN;
  }

  public void setInstanceIdDotN(List<String> instanceIdDotN) {
    this.instanceIdDotN = instanceIdDotN;
  }

  public DeleteInstanceSnapshotsApiRequestSchema snapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
    return this;
  }

   /**
   * snapshot id
   * @return snapshotId
  **/
  @ApiModelProperty(value = "snapshot id")
  public String getSnapshotId() {
    return snapshotId;
  }

  public void setSnapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
  }

  public DeleteInstanceSnapshotsApiRequestSchema ownerIdN(List<String> ownerIdN) {
    this.ownerIdN = ownerIdN;
    return this;
  }

  public DeleteInstanceSnapshotsApiRequestSchema addOwnerIdNItem(String ownerIdNItem) {
    if (this.ownerIdN == null) {
      this.ownerIdN = new ArrayList<>();
    }
    this.ownerIdN.add(ownerIdNItem);
    return this;
  }

   /**
   * account ID of the instance owner
   * @return ownerIdN
  **/
  @ApiModelProperty(value = "account ID of the instance owner")
  public List<String> getOwnerIdN() {
    return ownerIdN;
  }

  public void setOwnerIdN(List<String> ownerIdN) {
    this.ownerIdN = ownerIdN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteInstanceSnapshotsApiRequestSchema deleteInstanceSnapshotsApiRequestSchema = (DeleteInstanceSnapshotsApiRequestSchema) o;
    return Objects.equals(this.instanceIdDotN, deleteInstanceSnapshotsApiRequestSchema.instanceIdDotN) &&
        Objects.equals(this.snapshotId, deleteInstanceSnapshotsApiRequestSchema.snapshotId) &&
        Objects.equals(this.ownerIdN, deleteInstanceSnapshotsApiRequestSchema.ownerIdN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceIdDotN, snapshotId, ownerIdN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteInstanceSnapshotsApiRequestSchema {\n");
    
    sb.append("    instanceIdDotN: ").append(toIndentedString(instanceIdDotN)).append("\n");
    sb.append("    snapshotId: ").append(toIndentedString(snapshotId)).append("\n");
    sb.append("    ownerIdN: ").append(toIndentedString(ownerIdN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

