/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet
 */

public class DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet {
  @JsonProperty("cidrBlock")
  private String cidrBlock = null;

  @JsonProperty("cidrBlockAssociationSet")
  private List<DescribeVpcsResponseSchemaDescribeVpcsResponseCidrBlockAssociationSet> cidrBlockAssociationSet = null;

  @JsonProperty("dhcpOptionsId")
  private String dhcpOptionsId = null;

  /**
   * allowed tenancy of instances launched into the VPC
   */
  public enum InstanceTenancyEnum {
    DEFAULT("default"),
    
    DEDICATED("dedicated"),
    
    HOST("host");

    private String value;

    InstanceTenancyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InstanceTenancyEnum fromValue(String value) {
      for (InstanceTenancyEnum b : InstanceTenancyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("instanceTenancy")
  private InstanceTenancyEnum instanceTenancy = null;

  @JsonProperty("ipv6CidrBlockAssociationSet")
  private List<Object> ipv6CidrBlockAssociationSet = null;

  @JsonProperty("isDefault")
  private Boolean isDefault = null;

  @JsonProperty("nvl-name")
  private String nvlName = null;

  @JsonProperty("nvl-resourceId")
  private String nvlResourceId = null;

  @JsonProperty("nvl-vpcName")
  private String nvlVpcName = null;

  @JsonProperty("nvl-vpcOwnerAlias")
  private String nvlVpcOwnerAlias = null;

  @JsonProperty("nvl-vpcOwnerId")
  private String nvlVpcOwnerId = null;

  @JsonProperty("ownerId")
  private String ownerId = null;

  /**
   * state of the VPC (pending | available | transient | error)
   */
  public enum StateEnum {
    AVAILABLE("available"),
    
    DEREGISTERED("deregistered"),
    
    ERROR("error"),
    
    PENDING("pending"),
    
    TRANSIENT("transient"),
    
    UNKNOWN("unknown");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("tagSet")
  private List<DescribeImagesResponseSchemaDescribeImagesResponseTagSet> tagSet = null;

  @JsonProperty("vpcId")
  private String vpcId = null;

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet cidrBlock(String cidrBlock) {
    this.cidrBlock = cidrBlock;
    return this;
  }

   /**
   * primary IPv4 CIDR block for the VPC
   * @return cidrBlock
  **/
  @ApiModelProperty(example = "", value = "primary IPv4 CIDR block for the VPC")
  public String getCidrBlock() {
    return cidrBlock;
  }

  public void setCidrBlock(String cidrBlock) {
    this.cidrBlock = cidrBlock;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet cidrBlockAssociationSet(List<DescribeVpcsResponseSchemaDescribeVpcsResponseCidrBlockAssociationSet> cidrBlockAssociationSet) {
    this.cidrBlockAssociationSet = cidrBlockAssociationSet;
    return this;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet addCidrBlockAssociationSetItem(DescribeVpcsResponseSchemaDescribeVpcsResponseCidrBlockAssociationSet cidrBlockAssociationSetItem) {
    if (this.cidrBlockAssociationSet == null) {
      this.cidrBlockAssociationSet = new ArrayList<>();
    }
    this.cidrBlockAssociationSet.add(cidrBlockAssociationSetItem);
    return this;
  }

   /**
   * IPv4 CIDR blocks associated with the VPC
   * @return cidrBlockAssociationSet
  **/
  @ApiModelProperty(value = "IPv4 CIDR blocks associated with the VPC")
  public List<DescribeVpcsResponseSchemaDescribeVpcsResponseCidrBlockAssociationSet> getCidrBlockAssociationSet() {
    return cidrBlockAssociationSet;
  }

  public void setCidrBlockAssociationSet(List<DescribeVpcsResponseSchemaDescribeVpcsResponseCidrBlockAssociationSet> cidrBlockAssociationSet) {
    this.cidrBlockAssociationSet = cidrBlockAssociationSet;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet dhcpOptionsId(String dhcpOptionsId) {
    this.dhcpOptionsId = dhcpOptionsId;
    return this;
  }

   /**
   * ID of the set of DHCP options associated with VPC
   * @return dhcpOptionsId
  **/
  @ApiModelProperty(example = "", value = "ID of the set of DHCP options associated with VPC")
  public String getDhcpOptionsId() {
    return dhcpOptionsId;
  }

  public void setDhcpOptionsId(String dhcpOptionsId) {
    this.dhcpOptionsId = dhcpOptionsId;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet instanceTenancy(InstanceTenancyEnum instanceTenancy) {
    this.instanceTenancy = instanceTenancy;
    return this;
  }

   /**
   * allowed tenancy of instances launched into the VPC
   * @return instanceTenancy
  **/
  @ApiModelProperty(example = "", value = "allowed tenancy of instances launched into the VPC")
  public InstanceTenancyEnum getInstanceTenancy() {
    return instanceTenancy;
  }

  public void setInstanceTenancy(InstanceTenancyEnum instanceTenancy) {
    this.instanceTenancy = instanceTenancy;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet ipv6CidrBlockAssociationSet(List<Object> ipv6CidrBlockAssociationSet) {
    this.ipv6CidrBlockAssociationSet = ipv6CidrBlockAssociationSet;
    return this;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet addIpv6CidrBlockAssociationSetItem(Object ipv6CidrBlockAssociationSetItem) {
    if (this.ipv6CidrBlockAssociationSet == null) {
      this.ipv6CidrBlockAssociationSet = new ArrayList<>();
    }
    this.ipv6CidrBlockAssociationSet.add(ipv6CidrBlockAssociationSetItem);
    return this;
  }

   /**
   * IPv6 CIDR blocks associated with the VPC
   * @return ipv6CidrBlockAssociationSet
  **/
  @ApiModelProperty(value = "IPv6 CIDR blocks associated with the VPC")
  public List<Object> getIpv6CidrBlockAssociationSet() {
    return ipv6CidrBlockAssociationSet;
  }

  public void setIpv6CidrBlockAssociationSet(List<Object> ipv6CidrBlockAssociationSet) {
    this.ipv6CidrBlockAssociationSet = ipv6CidrBlockAssociationSet;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Indicates whether the VPC is the default VPC
   * @return isDefault
  **/
  @ApiModelProperty(value = "Indicates whether the VPC is the default VPC")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet nvlName(String nvlName) {
    this.nvlName = nvlName;
    return this;
  }

   /**
   * Get nvlName
   * @return nvlName
  **/
  @ApiModelProperty(example = "", value = "")
  public String getNvlName() {
    return nvlName;
  }

  public void setNvlName(String nvlName) {
    this.nvlName = nvlName;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet nvlResourceId(String nvlResourceId) {
    this.nvlResourceId = nvlResourceId;
    return this;
  }

   /**
   * Get nvlResourceId
   * @return nvlResourceId
  **/
  @ApiModelProperty(example = "", value = "")
  public String getNvlResourceId() {
    return nvlResourceId;
  }

  public void setNvlResourceId(String nvlResourceId) {
    this.nvlResourceId = nvlResourceId;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet nvlVpcName(String nvlVpcName) {
    this.nvlVpcName = nvlVpcName;
    return this;
  }

   /**
   * Get nvlVpcName
   * @return nvlVpcName
  **/
  @ApiModelProperty(example = "", value = "")
  public String getNvlVpcName() {
    return nvlVpcName;
  }

  public void setNvlVpcName(String nvlVpcName) {
    this.nvlVpcName = nvlVpcName;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet nvlVpcOwnerAlias(String nvlVpcOwnerAlias) {
    this.nvlVpcOwnerAlias = nvlVpcOwnerAlias;
    return this;
  }

   /**
   * Get nvlVpcOwnerAlias
   * @return nvlVpcOwnerAlias
  **/
  @ApiModelProperty(example = "", value = "")
  public String getNvlVpcOwnerAlias() {
    return nvlVpcOwnerAlias;
  }

  public void setNvlVpcOwnerAlias(String nvlVpcOwnerAlias) {
    this.nvlVpcOwnerAlias = nvlVpcOwnerAlias;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet nvlVpcOwnerId(String nvlVpcOwnerId) {
    this.nvlVpcOwnerId = nvlVpcOwnerId;
    return this;
  }

   /**
   * Get nvlVpcOwnerId
   * @return nvlVpcOwnerId
  **/
  @ApiModelProperty(example = "", value = "")
  public String getNvlVpcOwnerId() {
    return nvlVpcOwnerId;
  }

  public void setNvlVpcOwnerId(String nvlVpcOwnerId) {
    this.nvlVpcOwnerId = nvlVpcOwnerId;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @ApiModelProperty(example = "", value = "")
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * state of the VPC (pending | available | transient | error)
   * @return state
  **/
  @ApiModelProperty(example = "pending", value = "state of the VPC (pending | available | transient | error)")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet tagSet(List<DescribeImagesResponseSchemaDescribeImagesResponseTagSet> tagSet) {
    this.tagSet = tagSet;
    return this;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet addTagSetItem(DescribeImagesResponseSchemaDescribeImagesResponseTagSet tagSetItem) {
    if (this.tagSet == null) {
      this.tagSet = new ArrayList<>();
    }
    this.tagSet.add(tagSetItem);
    return this;
  }

   /**
   * Get tagSet
   * @return tagSet
  **/
  @ApiModelProperty(value = "")
  public List<DescribeImagesResponseSchemaDescribeImagesResponseTagSet> getTagSet() {
    return tagSet;
  }

  public void setTagSet(List<DescribeImagesResponseSchemaDescribeImagesResponseTagSet> tagSet) {
    this.tagSet = tagSet;
  }

  public DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet vpcId(String vpcId) {
    this.vpcId = vpcId;
    return this;
  }

   /**
   * ID of the VPC
   * @return vpcId
  **/
  @ApiModelProperty(example = "12", value = "ID of the VPC")
  public String getVpcId() {
    return vpcId;
  }

  public void setVpcId(String vpcId) {
    this.vpcId = vpcId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet describeVpcsResponseSchemaDescribeVpcsResponseVpcSet = (DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet) o;
    return Objects.equals(this.cidrBlock, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.cidrBlock) &&
        Objects.equals(this.cidrBlockAssociationSet, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.cidrBlockAssociationSet) &&
        Objects.equals(this.dhcpOptionsId, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.dhcpOptionsId) &&
        Objects.equals(this.instanceTenancy, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.instanceTenancy) &&
        Objects.equals(this.ipv6CidrBlockAssociationSet, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.ipv6CidrBlockAssociationSet) &&
        Objects.equals(this.isDefault, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.isDefault) &&
        Objects.equals(this.nvlName, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.nvlName) &&
        Objects.equals(this.nvlResourceId, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.nvlResourceId) &&
        Objects.equals(this.nvlVpcName, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.nvlVpcName) &&
        Objects.equals(this.nvlVpcOwnerAlias, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.nvlVpcOwnerAlias) &&
        Objects.equals(this.nvlVpcOwnerId, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.nvlVpcOwnerId) &&
        Objects.equals(this.ownerId, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.ownerId) &&
        Objects.equals(this.state, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.state) &&
        Objects.equals(this.tagSet, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.tagSet) &&
        Objects.equals(this.vpcId, describeVpcsResponseSchemaDescribeVpcsResponseVpcSet.vpcId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cidrBlock, cidrBlockAssociationSet, dhcpOptionsId, instanceTenancy, ipv6CidrBlockAssociationSet, isDefault, nvlName, nvlResourceId, nvlVpcName, nvlVpcOwnerAlias, nvlVpcOwnerId, ownerId, state, tagSet, vpcId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeVpcsResponseSchemaDescribeVpcsResponseVpcSet {\n");
    
    sb.append("    cidrBlock: ").append(toIndentedString(cidrBlock)).append("\n");
    sb.append("    cidrBlockAssociationSet: ").append(toIndentedString(cidrBlockAssociationSet)).append("\n");
    sb.append("    dhcpOptionsId: ").append(toIndentedString(dhcpOptionsId)).append("\n");
    sb.append("    instanceTenancy: ").append(toIndentedString(instanceTenancy)).append("\n");
    sb.append("    ipv6CidrBlockAssociationSet: ").append(toIndentedString(ipv6CidrBlockAssociationSet)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    nvlName: ").append(toIndentedString(nvlName)).append("\n");
    sb.append("    nvlResourceId: ").append(toIndentedString(nvlResourceId)).append("\n");
    sb.append("    nvlVpcName: ").append(toIndentedString(nvlVpcName)).append("\n");
    sb.append("    nvlVpcOwnerAlias: ").append(toIndentedString(nvlVpcOwnerAlias)).append("\n");
    sb.append("    nvlVpcOwnerId: ").append(toIndentedString(nvlVpcOwnerId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    tagSet: ").append(toIndentedString(tagSet)).append("\n");
    sb.append("    vpcId: ").append(toIndentedString(vpcId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

