/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints
 */

public class DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints {
  @JsonProperty("discover")
  private String discover = null;

  @JsonProperty("home")
  private String home = null;

  public DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints discover(String discover) {
    this.discover = discover;
    return this;
  }

   /**
   * space discover view endpoint
   * @return discover
  **/
  @ApiModelProperty(example = "https://localhost/s/prova/app/discover#/", required = true, value = "space discover view endpoint")
  public String getDiscover() {
    return discover;
  }

  public void setDiscover(String discover) {
    this.discover = discover;
  }

  public DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints home(String home) {
    this.home = home;
    return this;
  }

   /**
   * space home endpoint
   * @return home
  **/
  @ApiModelProperty(example = "https://localhost/s/prova/app/home#/", required = true, value = "space home endpoint")
  public String getHome() {
    return home;
  }

  public void setHome(String home) {
    this.home = home;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints describeSpacesResponseSchemaDescribeSpacesResponseEndpoints = (DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints) o;
    return Objects.equals(this.discover, describeSpacesResponseSchemaDescribeSpacesResponseEndpoints.discover) &&
        Objects.equals(this.home, describeSpacesResponseSchemaDescribeSpacesResponseEndpoints.home);
  }

  @Override
  public int hashCode() {
    return Objects.hash(discover, home);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeSpacesResponseSchemaDescribeSpacesResponseEndpoints {\n");
    
    sb.append("    discover: ").append(toIndentedString(discover)).append("\n");
    sb.append("    home: ").append(toIndentedString(home)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

