/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeSubnetsResponseSchemaDescribeSubnetsResponse
 */

public class DescribeSubnetsResponseSchemaDescribeSubnetsResponse {
  @JsonProperty("nvl-subnetTotal")
  private Integer nvlSubnetTotal = null;

  @JsonProperty("requestId")
  private String requestId = null;

  @JsonProperty("subnetSet")
  private List<DescribeSubnetsResponseSchemaDescribeSubnetsResponseSubnetSet> subnetSet = new ArrayList<>();

  public DescribeSubnetsResponseSchemaDescribeSubnetsResponse nvlSubnetTotal(Integer nvlSubnetTotal) {
    this.nvlSubnetTotal = nvlSubnetTotal;
    return this;
  }

   /**
   * total number of subnet
   * @return nvlSubnetTotal
  **/
  @ApiModelProperty(example = "", required = true, value = "total number of subnet")
  public Integer getNvlSubnetTotal() {
    return nvlSubnetTotal;
  }

  public void setNvlSubnetTotal(Integer nvlSubnetTotal) {
    this.nvlSubnetTotal = nvlSubnetTotal;
  }

  public DescribeSubnetsResponseSchemaDescribeSubnetsResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * 
   * @return requestId
  **/
  @ApiModelProperty(example = "", required = true, value = "")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public DescribeSubnetsResponseSchemaDescribeSubnetsResponse subnetSet(List<DescribeSubnetsResponseSchemaDescribeSubnetsResponseSubnetSet> subnetSet) {
    this.subnetSet = subnetSet;
    return this;
  }

  public DescribeSubnetsResponseSchemaDescribeSubnetsResponse addSubnetSetItem(DescribeSubnetsResponseSchemaDescribeSubnetsResponseSubnetSet subnetSetItem) {
    this.subnetSet.add(subnetSetItem);
    return this;
  }

   /**
   * Get subnetSet
   * @return subnetSet
  **/
  @ApiModelProperty(required = true, value = "")
  public List<DescribeSubnetsResponseSchemaDescribeSubnetsResponseSubnetSet> getSubnetSet() {
    return subnetSet;
  }

  public void setSubnetSet(List<DescribeSubnetsResponseSchemaDescribeSubnetsResponseSubnetSet> subnetSet) {
    this.subnetSet = subnetSet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeSubnetsResponseSchemaDescribeSubnetsResponse describeSubnetsResponseSchemaDescribeSubnetsResponse = (DescribeSubnetsResponseSchemaDescribeSubnetsResponse) o;
    return Objects.equals(this.nvlSubnetTotal, describeSubnetsResponseSchemaDescribeSubnetsResponse.nvlSubnetTotal) &&
        Objects.equals(this.requestId, describeSubnetsResponseSchemaDescribeSubnetsResponse.requestId) &&
        Objects.equals(this.subnetSet, describeSubnetsResponseSchemaDescribeSubnetsResponse.subnetSet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nvlSubnetTotal, requestId, subnetSet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeSubnetsResponseSchemaDescribeSubnetsResponse {\n");
    
    sb.append("    nvlSubnetTotal: ").append(toIndentedString(nvlSubnetTotal)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    subnetSet: ").append(toIndentedString(subnetSet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

