/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * state description
 */
@ApiModel(description = "state description")

public class DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("message")
  private String message = null;

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * state code
   * @return code
  **/
  @ApiModelProperty(example = "", value = "state code")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason message(String message) {
    this.message = message;
    return this;
  }

   /**
   * state message
   * @return message
  **/
  @ApiModelProperty(example = "", value = "state message")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason describeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason = (DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason) o;
    return Objects.equals(this.code, describeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason.code) &&
        Objects.equals(this.message, describeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

