/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.time.LocalDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet
 */

public class DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet {
  @JsonProperty("creationDate")
  private LocalDateTime creationDate = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("owner_name")
  private String ownerName = null;

  @JsonProperty("resource_uuid")
  private String resourceUuid = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("stateReason")
  private DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason stateReason = null;

  @JsonProperty("template")
  private String template = null;

  @JsonProperty("template_name")
  private String templateName = null;

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet creationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * creation date
   * @return creationDate
  **/
  @ApiModelProperty(example = "2022-01-25T11:20:18Z", required = true, value = "creation date")
  public LocalDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet ownerName(String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

   /**
   * Get ownerName
   * @return ownerName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOwnerName() {
    return ownerName;
  }

  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet resourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
    return this;
  }

   /**
   * Get resourceUuid
   * @return resourceUuid
  **/
  @ApiModelProperty(value = "")
  public String getResourceUuid() {
    return resourceUuid;
  }

  public void setResourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet stateReason(DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason stateReason) {
    this.stateReason = stateReason;
    return this;
  }

   /**
   * Get stateReason
   * @return stateReason
  **/
  @ApiModelProperty(required = true, value = "")
  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason getStateReason() {
    return stateReason;
  }

  public void setStateReason(DescribeLoggingServiceResponseSchemaDescribeLoggingResponseStateReason stateReason) {
    this.stateReason = stateReason;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet template(String template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet templateName(String templateName) {
    this.templateName = templateName;
    return this;
  }

   /**
   * Get templateName
   * @return templateName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplateName() {
    return templateName;
  }

  public void setTemplateName(String templateName) {
    this.templateName = templateName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet = (DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet) o;
    return Objects.equals(this.creationDate, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.creationDate) &&
        Objects.equals(this.description, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.description) &&
        Objects.equals(this.id, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.id) &&
        Objects.equals(this.name, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.name) &&
        Objects.equals(this.owner, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.owner) &&
        Objects.equals(this.ownerName, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.ownerName) &&
        Objects.equals(this.resourceUuid, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.resourceUuid) &&
        Objects.equals(this.state, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.state) &&
        Objects.equals(this.stateReason, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.stateReason) &&
        Objects.equals(this.template, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.template) &&
        Objects.equals(this.templateName, describeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet.templateName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, description, id, name, owner, ownerName, resourceUuid, state, stateReason, template, templateName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeLoggingServiceResponseSchemaDescribeLoggingResponseLoggingSet {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    resourceUuid: ").append(toIndentedString(resourceUuid)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    stateReason: ").append(toIndentedString(stateReason)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

