/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion
 */

public class DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion {
  @JsonProperty("nvl-name")
  private String nvlName = null;

  @JsonProperty("nvl-state")
  private String nvlState = null;

  public DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion nvlName(String nvlName) {
    this.nvlName = nvlName;
    return this;
  }

   /**
   * Get nvlName
   * @return nvlName
  **/
  @ApiModelProperty(example = "test", value = "")
  public String getNvlName() {
    return nvlName;
  }

  public void setNvlName(String nvlName) {
    this.nvlName = nvlName;
  }

  public DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion nvlState(String nvlState) {
    this.nvlState = nvlState;
    return this;
  }

   /**
   * state of the gateway bastion
   * @return nvlState
  **/
  @ApiModelProperty(example = "pending", value = "state of the gateway bastion")
  public String getNvlState() {
    return nvlState;
  }

  public void setNvlState(String nvlState) {
    this.nvlState = nvlState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion describeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion = (DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion) o;
    return Objects.equals(this.nvlName, describeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion.nvlName) &&
        Objects.equals(this.nvlState, describeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion.nvlState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nvlName, nvlState);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeInternetGatewayBastionResponseSchemaDescribeInternetGatewayBastionResponseInternetGatewayBastion {\n");
    
    sb.append("    nvlName: ").append(toIndentedString(nvlName)).append("\n");
    sb.append("    nvlState: ").append(toIndentedString(nvlState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

