/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeDBInstanceSchemaApiV2ResponseSchema
 */

public class DescribeDBInstanceSchemaApiV2ResponseSchema {
  @JsonProperty("DescribeDBInstanceSchemaResponse")
  private DescribeDBInstanceSchemaApiV2ResponseSchemaDescribeDBInstanceSchemaResponse describeDBInstanceSchemaResponse = null;

  public DescribeDBInstanceSchemaApiV2ResponseSchema describeDBInstanceSchemaResponse(DescribeDBInstanceSchemaApiV2ResponseSchemaDescribeDBInstanceSchemaResponse describeDBInstanceSchemaResponse) {
    this.describeDBInstanceSchemaResponse = describeDBInstanceSchemaResponse;
    return this;
  }

   /**
   * Get describeDBInstanceSchemaResponse
   * @return describeDBInstanceSchemaResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public DescribeDBInstanceSchemaApiV2ResponseSchemaDescribeDBInstanceSchemaResponse getDescribeDBInstanceSchemaResponse() {
    return describeDBInstanceSchemaResponse;
  }

  public void setDescribeDBInstanceSchemaResponse(DescribeDBInstanceSchemaApiV2ResponseSchemaDescribeDBInstanceSchemaResponse describeDBInstanceSchemaResponse) {
    this.describeDBInstanceSchemaResponse = describeDBInstanceSchemaResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeDBInstanceSchemaApiV2ResponseSchema describeDBInstanceSchemaApiV2ResponseSchema = (DescribeDBInstanceSchemaApiV2ResponseSchema) o;
    return Objects.equals(this.describeDBInstanceSchemaResponse, describeDBInstanceSchemaApiV2ResponseSchema.describeDBInstanceSchemaResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(describeDBInstanceSchemaResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeDBInstanceSchemaApiV2ResponseSchema {\n");
    
    sb.append("    describeDBInstanceSchemaResponse: ").append(toIndentedString(describeDBInstanceSchemaResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

