/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeBackupJobsRequestSchema
 */

public class DescribeBackupJobsRequestSchema {
  @JsonProperty("JobId")
  private String jobId = null;

  @JsonProperty("owner-id.N")
  private List<String> ownerIdN = new ArrayList<>();

  public DescribeBackupJobsRequestSchema jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * backup job id
   * @return jobId
  **/
  @ApiModelProperty(example = "34r5tfgyyg", value = "backup job id")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public DescribeBackupJobsRequestSchema ownerIdN(List<String> ownerIdN) {
    this.ownerIdN = ownerIdN;
    return this;
  }

  public DescribeBackupJobsRequestSchema addOwnerIdNItem(String ownerIdNItem) {
    this.ownerIdN.add(ownerIdNItem);
    return this;
  }

   /**
   * account ID of the job owner
   * @return ownerIdN
  **/
  @ApiModelProperty(required = true, value = "account ID of the job owner")
  public List<String> getOwnerIdN() {
    return ownerIdN;
  }

  public void setOwnerIdN(List<String> ownerIdN) {
    this.ownerIdN = ownerIdN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeBackupJobsRequestSchema describeBackupJobsRequestSchema = (DescribeBackupJobsRequestSchema) o;
    return Objects.equals(this.jobId, describeBackupJobsRequestSchema.jobId) &&
        Objects.equals(this.ownerIdN, describeBackupJobsRequestSchema.ownerIdN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, ownerIdN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeBackupJobsRequestSchema {\n");
    
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    ownerIdN: ").append(toIndentedString(ownerIdN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

