/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeInstancesV20ApiResponseSchema
 */

public class DescribeInstancesV20ApiResponseSchema {
  @JsonProperty("DescribeInstancesResponse")
  private DescribeInstancesV20ApiResponseSchemaDescribeInstancesResponse describeInstancesResponse = null;

  public DescribeInstancesV20ApiResponseSchema describeInstancesResponse(DescribeInstancesV20ApiResponseSchemaDescribeInstancesResponse describeInstancesResponse) {
    this.describeInstancesResponse = describeInstancesResponse;
    return this;
  }

   /**
   * Get describeInstancesResponse
   * @return describeInstancesResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public DescribeInstancesV20ApiResponseSchemaDescribeInstancesResponse getDescribeInstancesResponse() {
    return describeInstancesResponse;
  }

  public void setDescribeInstancesResponse(DescribeInstancesV20ApiResponseSchemaDescribeInstancesResponse describeInstancesResponse) {
    this.describeInstancesResponse = describeInstancesResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeInstancesV20ApiResponseSchema describeInstancesV20ApiResponseSchema = (DescribeInstancesV20ApiResponseSchema) o;
    return Objects.equals(this.describeInstancesResponse, describeInstancesV20ApiResponseSchema.describeInstancesResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(describeInstancesResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeInstancesV20ApiResponseSchema {\n");
    
    sb.append("    describeInstancesResponse: ").append(toIndentedString(describeInstancesResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

