/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DescribeAccountAttributesCSResponseSchemaAccountAttributeSet
 */

public class DescribeAccountAttributesCSResponseSchemaAccountAttributeSet {
  @JsonProperty("attributeName")
  private String attributeName = null;

  @JsonProperty("attributeValueSet")
  private List<DescribeAccountAttributesCSResponseSchemaAttributeValueSet> attributeValueSet = null;

  @JsonProperty("nvl-attributeUnit")
  private String nvlAttributeUnit = null;

  public DescribeAccountAttributesCSResponseSchemaAccountAttributeSet attributeName(String attributeName) {
    this.attributeName = attributeName;
    return this;
  }

   /**
   * Get attributeName
   * @return attributeName
  **/
  @ApiModelProperty(value = "")
  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }

  public DescribeAccountAttributesCSResponseSchemaAccountAttributeSet attributeValueSet(List<DescribeAccountAttributesCSResponseSchemaAttributeValueSet> attributeValueSet) {
    this.attributeValueSet = attributeValueSet;
    return this;
  }

  public DescribeAccountAttributesCSResponseSchemaAccountAttributeSet addAttributeValueSetItem(DescribeAccountAttributesCSResponseSchemaAttributeValueSet attributeValueSetItem) {
    if (this.attributeValueSet == null) {
      this.attributeValueSet = new ArrayList<>();
    }
    this.attributeValueSet.add(attributeValueSetItem);
    return this;
  }

   /**
   * Get attributeValueSet
   * @return attributeValueSet
  **/
  @ApiModelProperty(value = "")
  public List<DescribeAccountAttributesCSResponseSchemaAttributeValueSet> getAttributeValueSet() {
    return attributeValueSet;
  }

  public void setAttributeValueSet(List<DescribeAccountAttributesCSResponseSchemaAttributeValueSet> attributeValueSet) {
    this.attributeValueSet = attributeValueSet;
  }

  public DescribeAccountAttributesCSResponseSchemaAccountAttributeSet nvlAttributeUnit(String nvlAttributeUnit) {
    this.nvlAttributeUnit = nvlAttributeUnit;
    return this;
  }

   /**
   * Get nvlAttributeUnit
   * @return nvlAttributeUnit
  **/
  @ApiModelProperty(value = "")
  public String getNvlAttributeUnit() {
    return nvlAttributeUnit;
  }

  public void setNvlAttributeUnit(String nvlAttributeUnit) {
    this.nvlAttributeUnit = nvlAttributeUnit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeAccountAttributesCSResponseSchemaAccountAttributeSet describeAccountAttributesCSResponseSchemaAccountAttributeSet = (DescribeAccountAttributesCSResponseSchemaAccountAttributeSet) o;
    return Objects.equals(this.attributeName, describeAccountAttributesCSResponseSchemaAccountAttributeSet.attributeName) &&
        Objects.equals(this.attributeValueSet, describeAccountAttributesCSResponseSchemaAccountAttributeSet.attributeValueSet) &&
        Objects.equals(this.nvlAttributeUnit, describeAccountAttributesCSResponseSchemaAccountAttributeSet.nvlAttributeUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeName, attributeValueSet, nvlAttributeUnit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeAccountAttributesCSResponseSchemaAccountAttributeSet {\n");
    
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    attributeValueSet: ").append(toIndentedString(attributeValueSet)).append("\n");
    sb.append("    nvlAttributeUnit: ").append(toIndentedString(nvlAttributeUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

