/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * EnableLogConfigApiRequestSchema
 */

public class EnableLogConfigApiRequestSchema {
  @JsonProperty("Config")
  private String config = null;

  @JsonProperty("InstanceId")
  private String instanceId = null;

  public EnableLogConfigApiRequestSchema config(String config) {
    this.config = config;
    return this;
  }

   /**
   * name of logging configuration
   * @return config
  **/
  @ApiModelProperty(example = "tomcat", value = "name of logging configuration")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }

  public EnableLogConfigApiRequestSchema instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * logging instance id
   * @return instanceId
  **/
  @ApiModelProperty(value = "logging instance id")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnableLogConfigApiRequestSchema enableLogConfigApiRequestSchema = (EnableLogConfigApiRequestSchema) o;
    return Objects.equals(this.config, enableLogConfigApiRequestSchema.config) &&
        Objects.equals(this.instanceId, enableLogConfigApiRequestSchema.instanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, instanceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnableLogConfigApiRequestSchema {\n");
    
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

