/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * GetInstantConsumeServiceResponseSchemaDataMetrics
 */

public class GetInstantConsumeServiceResponseSchemaDataMetrics {
  @JsonProperty("container_id")
  private String containerId = null;

  @JsonProperty("extraction_date")
  private LocalDateTime extractionDate = null;

  @JsonProperty("group_name")
  private String groupName = null;

  @JsonProperty("metric_type_name")
  private String metricTypeName = null;

  @JsonProperty("value")
  private BigDecimal value = null;

  public GetInstantConsumeServiceResponseSchemaDataMetrics containerId(String containerId) {
    this.containerId = containerId;
    return this;
  }

   /**
   * Get containerId
   * @return containerId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getContainerId() {
    return containerId;
  }

  public void setContainerId(String containerId) {
    this.containerId = containerId;
  }

  public GetInstantConsumeServiceResponseSchemaDataMetrics extractionDate(LocalDateTime extractionDate) {
    this.extractionDate = extractionDate;
    return this;
  }

   /**
   * Get extractionDate
   * @return extractionDate
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDateTime getExtractionDate() {
    return extractionDate;
  }

  public void setExtractionDate(LocalDateTime extractionDate) {
    this.extractionDate = extractionDate;
  }

  public GetInstantConsumeServiceResponseSchemaDataMetrics groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @ApiModelProperty(value = "")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public GetInstantConsumeServiceResponseSchemaDataMetrics metricTypeName(String metricTypeName) {
    this.metricTypeName = metricTypeName;
    return this;
  }

   /**
   * Get metricTypeName
   * @return metricTypeName
  **/
  @ApiModelProperty(value = "")
  public String getMetricTypeName() {
    return metricTypeName;
  }

  public void setMetricTypeName(String metricTypeName) {
    this.metricTypeName = metricTypeName;
  }

  public GetInstantConsumeServiceResponseSchemaDataMetrics value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInstantConsumeServiceResponseSchemaDataMetrics getInstantConsumeServiceResponseSchemaDataMetrics = (GetInstantConsumeServiceResponseSchemaDataMetrics) o;
    return Objects.equals(this.containerId, getInstantConsumeServiceResponseSchemaDataMetrics.containerId) &&
        Objects.equals(this.extractionDate, getInstantConsumeServiceResponseSchemaDataMetrics.extractionDate) &&
        Objects.equals(this.groupName, getInstantConsumeServiceResponseSchemaDataMetrics.groupName) &&
        Objects.equals(this.metricTypeName, getInstantConsumeServiceResponseSchemaDataMetrics.metricTypeName) &&
        Objects.equals(this.value, getInstantConsumeServiceResponseSchemaDataMetrics.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containerId, extractionDate, groupName, metricTypeName, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInstantConsumeServiceResponseSchemaDataMetrics {\n");
    
    sb.append("    containerId: ").append(toIndentedString(containerId)).append("\n");
    sb.append("    extractionDate: ").append(toIndentedString(extractionDate)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    metricTypeName: ").append(toIndentedString(metricTypeName)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

