/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * GetSchedulerEntriesResponseSchemaSchedules
 */

public class GetSchedulerEntriesResponseSchemaSchedules {
  @JsonProperty("args")
  private List<String> args = null;

  @JsonProperty("kwargs")
  private Object kwargs = null;

  @JsonProperty("last_run_at")
  private LocalDateTime lastRunAt = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("options")
  private Object options = null;

  @JsonProperty("schedule")
  private String schedule = null;

  @JsonProperty("schedules")
  private List<Object> schedules = new ArrayList<>();

  @JsonProperty("task")
  private String task = null;

  @JsonProperty("total_run_count")
  private Integer totalRunCount = null;

  public GetSchedulerEntriesResponseSchemaSchedules args(List<String> args) {
    this.args = args;
    return this;
  }

  public GetSchedulerEntriesResponseSchemaSchedules addArgsItem(String argsItem) {
    if (this.args == null) {
      this.args = new ArrayList<>();
    }
    this.args.add(argsItem);
    return this;
  }

   /**
   * Get args
   * @return args
  **/
  @ApiModelProperty(value = "")
  public List<String> getArgs() {
    return args;
  }

  public void setArgs(List<String> args) {
    this.args = args;
  }

  public GetSchedulerEntriesResponseSchemaSchedules kwargs(Object kwargs) {
    this.kwargs = kwargs;
    return this;
  }

   /**
   * Get kwargs
   * @return kwargs
  **/
  @ApiModelProperty(value = "")
  public Object getKwargs() {
    return kwargs;
  }

  public void setKwargs(Object kwargs) {
    this.kwargs = kwargs;
  }

  public GetSchedulerEntriesResponseSchemaSchedules lastRunAt(LocalDateTime lastRunAt) {
    this.lastRunAt = lastRunAt;
    return this;
  }

   /**
   * Get lastRunAt
   * @return lastRunAt
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDateTime getLastRunAt() {
    return lastRunAt;
  }

  public void setLastRunAt(LocalDateTime lastRunAt) {
    this.lastRunAt = lastRunAt;
  }

  public GetSchedulerEntriesResponseSchemaSchedules name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetSchedulerEntriesResponseSchemaSchedules options(Object options) {
    this.options = options;
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @ApiModelProperty(required = true, value = "")
  public Object getOptions() {
    return options;
  }

  public void setOptions(Object options) {
    this.options = options;
  }

  public GetSchedulerEntriesResponseSchemaSchedules schedule(String schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSchedule() {
    return schedule;
  }

  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }

  public GetSchedulerEntriesResponseSchemaSchedules schedules(List<Object> schedules) {
    this.schedules = schedules;
    return this;
  }

  public GetSchedulerEntriesResponseSchemaSchedules addSchedulesItem(Object schedulesItem) {
    this.schedules.add(schedulesItem);
    return this;
  }

   /**
   * Get schedules
   * @return schedules
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Object> getSchedules() {
    return schedules;
  }

  public void setSchedules(List<Object> schedules) {
    this.schedules = schedules;
  }

  public GetSchedulerEntriesResponseSchemaSchedules task(String task) {
    this.task = task;
    return this;
  }

   /**
   * Get task
   * @return task
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTask() {
    return task;
  }

  public void setTask(String task) {
    this.task = task;
  }

  public GetSchedulerEntriesResponseSchemaSchedules totalRunCount(Integer totalRunCount) {
    this.totalRunCount = totalRunCount;
    return this;
  }

   /**
   * Get totalRunCount
   * @return totalRunCount
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getTotalRunCount() {
    return totalRunCount;
  }

  public void setTotalRunCount(Integer totalRunCount) {
    this.totalRunCount = totalRunCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSchedulerEntriesResponseSchemaSchedules getSchedulerEntriesResponseSchemaSchedules = (GetSchedulerEntriesResponseSchemaSchedules) o;
    return Objects.equals(this.args, getSchedulerEntriesResponseSchemaSchedules.args) &&
        Objects.equals(this.kwargs, getSchedulerEntriesResponseSchemaSchedules.kwargs) &&
        Objects.equals(this.lastRunAt, getSchedulerEntriesResponseSchemaSchedules.lastRunAt) &&
        Objects.equals(this.name, getSchedulerEntriesResponseSchemaSchedules.name) &&
        Objects.equals(this.options, getSchedulerEntriesResponseSchemaSchedules.options) &&
        Objects.equals(this.schedule, getSchedulerEntriesResponseSchemaSchedules.schedule) &&
        Objects.equals(this.schedules, getSchedulerEntriesResponseSchemaSchedules.schedules) &&
        Objects.equals(this.task, getSchedulerEntriesResponseSchemaSchedules.task) &&
        Objects.equals(this.totalRunCount, getSchedulerEntriesResponseSchemaSchedules.totalRunCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, kwargs, lastRunAt, name, options, schedule, schedules, task, totalRunCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSchedulerEntriesResponseSchemaSchedules {\n");
    
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    kwargs: ").append(toIndentedString(kwargs)).append("\n");
    sb.append("    lastRunAt: ").append(toIndentedString(lastRunAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    schedules: ").append(toIndentedString(schedules)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    totalRunCount: ").append(toIndentedString(totalRunCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

