/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ListAccountCapabilitiesResponseSchemaParamsParams
 */

public class ListAccountCapabilitiesResponseSchemaParamsParams {
  @JsonProperty("cidr")
  private String cidr = null;

  @JsonProperty("vpc")
  private String vpc = null;

  @JsonProperty("zone")
  private String zone = null;

  public ListAccountCapabilitiesResponseSchemaParamsParams cidr(String cidr) {
    this.cidr = cidr;
    return this;
  }

   /**
   * Get cidr
   * @return cidr
  **/
  @ApiModelProperty(example = "10.138.236.96/27", value = "")
  public String getCidr() {
    return cidr;
  }

  public void setCidr(String cidr) {
    this.cidr = cidr;
  }

  public ListAccountCapabilitiesResponseSchemaParamsParams vpc(String vpc) {
    this.vpc = vpc;
    return this;
  }

   /**
   * Get vpc
   * @return vpc
  **/
  @ApiModelProperty(example = "VpcRUPAR04", value = "")
  public String getVpc() {
    return vpc;
  }

  public void setVpc(String vpc) {
    this.vpc = vpc;
  }

  public ListAccountCapabilitiesResponseSchemaParamsParams zone(String zone) {
    this.zone = zone;
    return this;
  }

   /**
   * Get zone
   * @return zone
  **/
  @ApiModelProperty(example = "SiteVercelli01", value = "")
  public String getZone() {
    return zone;
  }

  public void setZone(String zone) {
    this.zone = zone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAccountCapabilitiesResponseSchemaParamsParams listAccountCapabilitiesResponseSchemaParamsParams = (ListAccountCapabilitiesResponseSchemaParamsParams) o;
    return Objects.equals(this.cidr, listAccountCapabilitiesResponseSchemaParamsParams.cidr) &&
        Objects.equals(this.vpc, listAccountCapabilitiesResponseSchemaParamsParams.vpc) &&
        Objects.equals(this.zone, listAccountCapabilitiesResponseSchemaParamsParams.zone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cidr, vpc, zone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAccountCapabilitiesResponseSchemaParamsParams {\n");
    
    sb.append("    cidr: ").append(toIndentedString(cidr)).append("\n");
    sb.append("    vpc: ").append(toIndentedString(vpc)).append("\n");
    sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

