/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ModifyAccountAttributesResponseSchema
 */

public class ModifyAccountAttributesResponseSchema {
  @JsonProperty("ModifyAccountAttributesResponse")
  private DescribeAccountAttributesResponseSchemaDescribeAccountAttributesResponse modifyAccountAttributesResponse = null;

  public ModifyAccountAttributesResponseSchema modifyAccountAttributesResponse(DescribeAccountAttributesResponseSchemaDescribeAccountAttributesResponse modifyAccountAttributesResponse) {
    this.modifyAccountAttributesResponse = modifyAccountAttributesResponse;
    return this;
  }

   /**
   * Get modifyAccountAttributesResponse
   * @return modifyAccountAttributesResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public DescribeAccountAttributesResponseSchemaDescribeAccountAttributesResponse getModifyAccountAttributesResponse() {
    return modifyAccountAttributesResponse;
  }

  public void setModifyAccountAttributesResponse(DescribeAccountAttributesResponseSchemaDescribeAccountAttributesResponse modifyAccountAttributesResponse) {
    this.modifyAccountAttributesResponse = modifyAccountAttributesResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyAccountAttributesResponseSchema modifyAccountAttributesResponseSchema = (ModifyAccountAttributesResponseSchema) o;
    return Objects.equals(this.modifyAccountAttributesResponse, modifyAccountAttributesResponseSchema.modifyAccountAttributesResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modifyAccountAttributesResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyAccountAttributesResponseSchema {\n");
    
    sb.append("    modifyAccountAttributesResponse: ").append(toIndentedString(modifyAccountAttributesResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

