/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * MonitorInstancesApiRequestSchema
 */

public class MonitorInstancesApiRequestSchema {
  @JsonProperty("InstanceId.N")
  private List<String> instanceIdDotN = new ArrayList<>();

  @JsonProperty("Nvl_Templates")
  private List<String> nvlTemplates = null;

  @JsonProperty("owner-id.N")
  private List<String> ownerIdN = null;

  public MonitorInstancesApiRequestSchema instanceIdDotN(List<String> instanceIdDotN) {
    this.instanceIdDotN = instanceIdDotN;
    return this;
  }

  public MonitorInstancesApiRequestSchema addInstanceIdDotNItem(String instanceIdDotNItem) {
    this.instanceIdDotN.add(instanceIdDotNItem);
    return this;
  }

   /**
   * instance id
   * @return instanceIdDotN
  **/
  @ApiModelProperty(required = true, value = "instance id")
  public List<String> getInstanceIdDotN() {
    return instanceIdDotN;
  }

  public void setInstanceIdDotN(List<String> instanceIdDotN) {
    this.instanceIdDotN = instanceIdDotN;
  }

  public MonitorInstancesApiRequestSchema nvlTemplates(List<String> nvlTemplates) {
    this.nvlTemplates = nvlTemplates;
    return this;
  }

  public MonitorInstancesApiRequestSchema addNvlTemplatesItem(String nvlTemplatesItem) {
    if (this.nvlTemplates == null) {
      this.nvlTemplates = new ArrayList<>();
    }
    this.nvlTemplates.add(nvlTemplatesItem);
    return this;
  }

   /**
   * List of monitoring template
   * @return nvlTemplates
  **/
  @ApiModelProperty(value = "List of monitoring template")
  public List<String> getNvlTemplates() {
    return nvlTemplates;
  }

  public void setNvlTemplates(List<String> nvlTemplates) {
    this.nvlTemplates = nvlTemplates;
  }

  public MonitorInstancesApiRequestSchema ownerIdN(List<String> ownerIdN) {
    this.ownerIdN = ownerIdN;
    return this;
  }

  public MonitorInstancesApiRequestSchema addOwnerIdNItem(String ownerIdNItem) {
    if (this.ownerIdN == null) {
      this.ownerIdN = new ArrayList<>();
    }
    this.ownerIdN.add(ownerIdNItem);
    return this;
  }

   /**
   * account ID of the instance owner
   * @return ownerIdN
  **/
  @ApiModelProperty(value = "account ID of the instance owner")
  public List<String> getOwnerIdN() {
    return ownerIdN;
  }

  public void setOwnerIdN(List<String> ownerIdN) {
    this.ownerIdN = ownerIdN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonitorInstancesApiRequestSchema monitorInstancesApiRequestSchema = (MonitorInstancesApiRequestSchema) o;
    return Objects.equals(this.instanceIdDotN, monitorInstancesApiRequestSchema.instanceIdDotN) &&
        Objects.equals(this.nvlTemplates, monitorInstancesApiRequestSchema.nvlTemplates) &&
        Objects.equals(this.ownerIdN, monitorInstancesApiRequestSchema.ownerIdN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceIdDotN, nvlTemplates, ownerIdN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonitorInstancesApiRequestSchema {\n");
    
    sb.append("    instanceIdDotN: ").append(toIndentedString(instanceIdDotN)).append("\n");
    sb.append("    nvlTemplates: ").append(toIndentedString(nvlTemplates)).append("\n");
    sb.append("    ownerIdN: ").append(toIndentedString(ownerIdN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

