/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdateServiceInstanceRequestSchemaServiceinst
 */

public class UpdateServiceInstanceRequestSchemaServiceinst {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("parent_id")
  private String parentId = null;

  @JsonProperty("resource_uuid")
  private String resourceUuid = null;

  @JsonProperty("tags")
  private UpdateLinkRequestSchemaLinkTags tags = null;

  public UpdateServiceInstanceRequestSchemaServiceinst active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public UpdateServiceInstanceRequestSchemaServiceinst parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * id of the parent service instance
   * @return parentId
  **/
  @ApiModelProperty(value = "id of the parent service instance")
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public UpdateServiceInstanceRequestSchemaServiceinst resourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
    return this;
  }

   /**
   * uuid of the new resource
   * @return resourceUuid
  **/
  @ApiModelProperty(value = "uuid of the new resource")
  public String getResourceUuid() {
    return resourceUuid;
  }

  public void setResourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
  }

  public UpdateServiceInstanceRequestSchemaServiceinst tags(UpdateLinkRequestSchemaLinkTags tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public UpdateLinkRequestSchemaLinkTags getTags() {
    return tags;
  }

  public void setTags(UpdateLinkRequestSchemaLinkTags tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateServiceInstanceRequestSchemaServiceinst updateServiceInstanceRequestSchemaServiceinst = (UpdateServiceInstanceRequestSchemaServiceinst) o;
    return Objects.equals(this.active, updateServiceInstanceRequestSchemaServiceinst.active) &&
        Objects.equals(this.parentId, updateServiceInstanceRequestSchemaServiceinst.parentId) &&
        Objects.equals(this.resourceUuid, updateServiceInstanceRequestSchemaServiceinst.resourceUuid) &&
        Objects.equals(this.tags, updateServiceInstanceRequestSchemaServiceinst.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, parentId, resourceUuid, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateServiceInstanceRequestSchemaServiceinst {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    resourceUuid: ").append(toIndentedString(resourceUuid)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

