/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * Beehive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nivola.engineering@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdateServicePriceMetricRequestSchemaPriceMetric
 */

public class UpdateServicePriceMetricRequestSchemaPriceMetric {
  @JsonProperty("desc")
  private String desc = null;

  @JsonProperty("metric_type_id")
  private Integer metricTypeId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("price")
  private BigDecimal price = null;

  @JsonProperty("price_list_id")
  private Integer priceListId = null;

  @JsonProperty("thresholds")
  private List<CreateServicePriceMetricRequestSchemaPriceMetricThresholds> thresholds = null;

  /**
   * Gets or Sets timeUnit
   */
  public enum TimeUnitEnum {
    YEAR("YEAR"),
    
    MONTH("MONTH"),
    
    DAY("DAY"),
    
    HOUR("HOUR"),
    
    MINUTE("MINUTE"),
    
    SECOND("SECOND");

    private String value;

    TimeUnitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimeUnitEnum fromValue(String value) {
      for (TimeUnitEnum b : TimeUnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("time_unit")
  private TimeUnitEnum timeUnit = null;

  public UpdateServicePriceMetricRequestSchemaPriceMetric desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @ApiModelProperty(value = "")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric metricTypeId(Integer metricTypeId) {
    this.metricTypeId = metricTypeId;
    return this;
  }

   /**
   * Get metricTypeId
   * @return metricTypeId
  **/
  @ApiModelProperty(value = "")
  public Integer getMetricTypeId() {
    return metricTypeId;
  }

  public void setMetricTypeId(Integer metricTypeId) {
    this.metricTypeId = metricTypeId;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric priceListId(Integer priceListId) {
    this.priceListId = priceListId;
    return this;
  }

   /**
   * Get priceListId
   * @return priceListId
  **/
  @ApiModelProperty(value = "")
  public Integer getPriceListId() {
    return priceListId;
  }

  public void setPriceListId(Integer priceListId) {
    this.priceListId = priceListId;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric thresholds(List<CreateServicePriceMetricRequestSchemaPriceMetricThresholds> thresholds) {
    this.thresholds = thresholds;
    return this;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric addThresholdsItem(CreateServicePriceMetricRequestSchemaPriceMetricThresholds thresholdsItem) {
    if (this.thresholds == null) {
      this.thresholds = new ArrayList<>();
    }
    this.thresholds.add(thresholdsItem);
    return this;
  }

   /**
   * Get thresholds
   * @return thresholds
  **/
  @ApiModelProperty(value = "")
  public List<CreateServicePriceMetricRequestSchemaPriceMetricThresholds> getThresholds() {
    return thresholds;
  }

  public void setThresholds(List<CreateServicePriceMetricRequestSchemaPriceMetricThresholds> thresholds) {
    this.thresholds = thresholds;
  }

  public UpdateServicePriceMetricRequestSchemaPriceMetric timeUnit(TimeUnitEnum timeUnit) {
    this.timeUnit = timeUnit;
    return this;
  }

   /**
   * Get timeUnit
   * @return timeUnit
  **/
  @ApiModelProperty(value = "")
  public TimeUnitEnum getTimeUnit() {
    return timeUnit;
  }

  public void setTimeUnit(TimeUnitEnum timeUnit) {
    this.timeUnit = timeUnit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateServicePriceMetricRequestSchemaPriceMetric updateServicePriceMetricRequestSchemaPriceMetric = (UpdateServicePriceMetricRequestSchemaPriceMetric) o;
    return Objects.equals(this.desc, updateServicePriceMetricRequestSchemaPriceMetric.desc) &&
        Objects.equals(this.metricTypeId, updateServicePriceMetricRequestSchemaPriceMetric.metricTypeId) &&
        Objects.equals(this.name, updateServicePriceMetricRequestSchemaPriceMetric.name) &&
        Objects.equals(this.price, updateServicePriceMetricRequestSchemaPriceMetric.price) &&
        Objects.equals(this.priceListId, updateServicePriceMetricRequestSchemaPriceMetric.priceListId) &&
        Objects.equals(this.thresholds, updateServicePriceMetricRequestSchemaPriceMetric.thresholds) &&
        Objects.equals(this.timeUnit, updateServicePriceMetricRequestSchemaPriceMetric.timeUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desc, metricTypeId, name, price, priceListId, thresholds, timeUnit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateServicePriceMetricRequestSchemaPriceMetric {\n");
    
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    metricTypeId: ").append(toIndentedString(metricTypeId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceListId: ").append(toIndentedString(priceListId)).append("\n");
    sb.append("    thresholds: ").append(toIndentedString(thresholds)).append("\n");
    sb.append("    timeUnit: ").append(toIndentedString(timeUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

