spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://<hostname>
        jdbcUrl: jdbc:mariadb://<hostname>
        username:
        password:
        hikari:
            data-source-properties:
                cachePrepStmts: false
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

logoutInfo:
  CSI : 
  IPA : 
  SISTEMAPIEMONTE : 
  SPID : 

# TODO: punta a stage in attesa di averne uno di dev/test 
cmp:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 
    jdbcUrl: jdbc:mariadb://
    username: 
    password: 
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    main:
      banner-mode: LOG
    output:
      ansi:
        enabled: always
    application:
        name: nivolasp
    profiles:
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
        serialization.indent_output: true
    jndi:
      ignore: true
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    mail:
        host: mailfarm-app.csi.it
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
        basename: /WEB-INF/classes/messages
    thymeleaf:
        cache: false
        
security:
    basic:
        enabled: false
        
server:
    port: 3333
    session:
        cookie:
            http-only: true
            path: /

info:
    project:
        version: #project.version#

deploy:
  timestamp: #maven.build.timestamp#
  utente: # utente cosi' composto: <codice_fiscale>/<nome>/<cognome>/ tutto il resto non e' necessario modificarlo GLLLCN64H26L219U/Luciano/Gallo/CSI/20181015190239/2/jRryBU1Yk/d6gJwcD8fEOw==
  profile: #spring.profiles.active#
  devMode: true
  indirizzoServizio: <valid email address>
  aliasServizio: Nivola Support Center
  pathToFrontEnd : #pathToFrontEnd#
  docsBaseUrl: https://nivola-userguide.readthedocs.io/
  docsLang: it
  endpointControlloBatch: http://<hostname>/nivolabatch-0.0.1/gestione
  host: <smtp host>
  port: 25
  redirectTo : <url redirect to in case of authentication failure or session timed out>

businessApi:
  amazonClientId: 
  amazonSecretKey: 
  amazonReportBucket: 
  scopeValue: 
  audience: 
  privateKey : 
  host: 
  basePath: 