/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: me@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.auth;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * GetUserAtributesResponseSchema
 */

public class GetUserAtributesResponseSchema {
  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("user_attributes")
  private List<GetUserAtributesResponseSchemaUserAttributes> userAttributes = new ArrayList<>();

  public GetUserAtributesResponseSchema count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public GetUserAtributesResponseSchema userAttributes(List<GetUserAtributesResponseSchemaUserAttributes> userAttributes) {
    this.userAttributes = userAttributes;
    return this;
  }

  public GetUserAtributesResponseSchema addUserAttributesItem(GetUserAtributesResponseSchemaUserAttributes userAttributesItem) {
    this.userAttributes.add(userAttributesItem);
    return this;
  }

   /**
   * Get userAttributes
   * @return userAttributes
  **/
  @ApiModelProperty(required = true, value = "")
  public List<GetUserAtributesResponseSchemaUserAttributes> getUserAttributes() {
    return userAttributes;
  }

  public void setUserAttributes(List<GetUserAtributesResponseSchemaUserAttributes> userAttributes) {
    this.userAttributes = userAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUserAtributesResponseSchema getUserAtributesResponseSchema = (GetUserAtributesResponseSchema) o;
    return Objects.equals(this.count, getUserAtributesResponseSchema.count) &&
        Objects.equals(this.userAttributes, getUserAtributesResponseSchema.userAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, userAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserAtributesResponseSchema {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    userAttributes: ").append(toIndentedString(userAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

