/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: me@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.auth;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ListTokensResponseSchema
 */

public class ListTokensResponseSchema {
  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("tokens")
  private List<GetTokenResponseSchemaToken> tokens = new ArrayList<>();

  public ListTokensResponseSchema count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Token count
   * @return count
  **/
  @ApiModelProperty(example = "1", required = true, value = "Token count")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public ListTokensResponseSchema tokens(List<GetTokenResponseSchemaToken> tokens) {
    this.tokens = tokens;
    return this;
  }

  public ListTokensResponseSchema addTokensItem(GetTokenResponseSchemaToken tokensItem) {
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * Get tokens
   * @return tokens
  **/
  @ApiModelProperty(required = true, value = "")
  public List<GetTokenResponseSchemaToken> getTokens() {
    return tokens;
  }

  public void setTokens(List<GetTokenResponseSchemaToken> tokens) {
    this.tokens = tokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListTokensResponseSchema listTokensResponseSchema = (ListTokensResponseSchema) o;
    return Objects.equals(this.count, listTokensResponseSchema.count) &&
        Objects.equals(this.tokens, listTokensResponseSchema.tokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, tokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListTokensResponseSchema {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

