/*-
 * ========================LICENSE_START=================================
 * Api CMP
 * %%
 * Copyright (C) 2022 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * Beehive API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: me@csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.nivola.nivolasp.integration.rest.model.auth;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdateGroupRequestSchemaGroupRoles
 */

public class UpdateGroupRequestSchemaGroupRoles {
  @JsonProperty("append")
  private List<List<String>> append = null;

  @JsonProperty("remove")
  private List<String> remove = null;

  public UpdateGroupRequestSchemaGroupRoles append(List<List<String>> append) {
    this.append = append;
    return this;
  }

  public UpdateGroupRequestSchemaGroupRoles addAppendItem(List<String> appendItem) {
    if (this.append == null) {
      this.append = new ArrayList<>();
    }
    this.append.add(appendItem);
    return this;
  }

   /**
   * Get append
   * @return append
  **/
  @ApiModelProperty(value = "")
  public List<List<String>> getAppend() {
    return append;
  }

  public void setAppend(List<List<String>> append) {
    this.append = append;
  }

  public UpdateGroupRequestSchemaGroupRoles remove(List<String> remove) {
    this.remove = remove;
    return this;
  }

  public UpdateGroupRequestSchemaGroupRoles addRemoveItem(String removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

   /**
   * Get remove
   * @return remove
  **/
  @ApiModelProperty(value = "")
  public List<String> getRemove() {
    return remove;
  }

  public void setRemove(List<String> remove) {
    this.remove = remove;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateGroupRequestSchemaGroupRoles updateGroupRequestSchemaGroupRoles = (UpdateGroupRequestSchemaGroupRoles) o;
    return Objects.equals(this.append, updateGroupRequestSchemaGroupRoles.append) &&
        Objects.equals(this.remove, updateGroupRequestSchemaGroupRoles.remove);
  }

  @Override
  public int hashCode() {
    return Objects.hash(append, remove);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateGroupRequestSchemaGroupRoles {\n");
    
    sb.append("    append: ").append(toIndentedString(append)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

