# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    main:
      banner-mode: LOG
    output:
      ansi:
        enabled: always
    banner:
      location: classpath:bannerappj.txt
    profiles: 
        active: #spring.profiles.active#
    jmx:
        default-domain: com.application.name
        unique-names: true
    jackson:
        serialization.write_dates_as_timestamps: false
        serialization.indent_output: true
    jndi:
      ignore: true
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    mail:
        host:
        port:
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias nivolasp -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: nivolasp
# ===================================================================
deploy:
  timestamp: #maven.build.timestamp#
  utente: #user.name#
  profile: #spring.profiles.active#
  host: 
  port: 
  indirizzoServizio: 
  aliasServizio: Nivola Support Center
  pathToFrontEnd : 

scheduling:
    reportCostoGiornaliero: 0 0 7,22 * * *
    elaborazioneCSVSTAAS: 0 15/30 6-22 * * *
     
staasCSV:
  elaborazionefile: true
  headerLineV01: DATE;FILER;FILESYSTEM;SHARE;USAGE(GB);LIMIT(GB)
  headerLineV02: DATE;VSERVER;FILESYSTEM;SHARE;SHAREUSED(GB);CAPACITY(GB)
  pathFilesCostiStaasDaCaricare: D:\\prova\\staas\\
  pathFilesCostiStaasCaricati: D:\\prova\\staas\\caricati\\
  pathFilesCostiStaasConErrore: D:\\prova\\staas\\inerrore\\
  pathFilesCostiStaasInProgress: D:\\prova\\staas\\inprogress\\